'use client'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Textarea} from '@/components/ui/textarea'
import {intentSchema,type Brief} from '@/lib/outreach/agents/core'
export function BriefReferenceFields({claims,faqs,onClaims,onFaqs,disabled}:{claims:Brief['claims'];faqs:Brief['faqs'];onClaims:(v:Brief['claims'])=>void;onFaqs:(v:Brief['faqs'])=>void;disabled:boolean}){
 return <div className="space-y-5"><fieldset disabled={disabled} className="space-y-3"><legend className="font-medium">Approved claims and evidence</legend>{claims.map((claim,i)=><div key={claim.id} className="space-y-2 rounded border p-3"><label className="block">Claim {i+1} text<Textarea value={claim.text} onChange={e=>onClaims(claims.map(c=>c.id===claim.id?{...c,text:e.target.value}:c))}/></label><label className="block">Claim {i+1} evidence<Input value={claim.evidence} onChange={e=>onClaims(claims.map(c=>c.id===claim.id?{...c,evidence:e.target.value}:c))}/></label><label className="block">Claim {i+1} source reference<Input value={claim.source} onChange={e=>onClaims(claims.map(c=>c.id===claim.id?{...c,source:e.target.value}:c))}/></label><Button variant="outline" onClick={()=>onClaims(claims.filter(c=>c.id!==claim.id))}>Remove claim {i+1}</Button></div>)}<Button variant="outline" disabled={disabled||claims.length>=30} onClick={()=>onClaims([...claims,{id:crypto.randomUUID(),text:'',evidence:'',source:''}])}>Add approved claim</Button></fieldset>
 <fieldset disabled={disabled} className="space-y-3"><legend className="font-medium">Approved FAQ replies</legend>{faqs.map((faq,i)=><div key={faq.id} className="space-y-2 rounded border p-3"><label className="block">FAQ {i+1} question<Input value={faq.question} onChange={e=>onFaqs(faqs.map(f=>f.id===faq.id?{...f,question:e.target.value}:f))}/></label><label className="block">FAQ {i+1} intent<select className="block w-full rounded border bg-background p-2" value={faq.intent} onChange={e=>onFaqs(faqs.map(f=>f.id===faq.id?{...f,intent:intentSchema.parse(e.target.value)}:f))}><option value="question">Question</option><option value="interested">Interested</option><option value="objection">Objection</option>{!['question','interested','objection'].includes(faq.intent)&&<option value={faq.intent}>{faq.intent} (manual review)</option>}</select></label><label className="block">FAQ {i+1} approved answer<Textarea rows={3} value={faq.answer} onChange={e=>onFaqs(faqs.map(f=>f.id===faq.id?{...f,answer:e.target.value}:f))}/></label><Button variant="outline" onClick={()=>onFaqs(faqs.filter(f=>f.id!==faq.id))}>Remove FAQ {i+1}</Button></div>)}<Button variant="outline" disabled={disabled||faqs.length>=30} onClick={()=>onFaqs([...faqs,{id:crypto.randomUUID(),intent:'question',question:'',answer:''}])}>Add FAQ reply</Button></fieldset></div>
}
