'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {z} from 'zod'
import {Input} from '@/components/ui/input'
import {Button} from '@/components/ui/button'
const responseSchema=z.object({threads:z.array(z.object({id:z.string(),subject:z.string().nullable(),participantEmail:z.string(),participantName:z.string().nullable().optional()})),pagination:z.object({totalPages:z.number()})})
export function ConversationPicker({value,onChange,disabled}:{value:string;onChange:(id:string)=>void;disabled:boolean}){
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[requestVersion,setRequestVersion]=useState(0),[data,setData]=useState<z.infer<typeof responseSchema>|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/inbox?${new URLSearchParams({page:String(page),limit:'50',search,status:'active'})}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error('Inbox unavailable');return responseSchema.parse(await response.json())}).then(value=>{if(!controller.signal.aborted)setData(value)}).catch(()=>{if(!controller.signal.aborted)setError('Unable to load conversations. Open the inbox or try again.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[page,search,requestVersion])
 return <div className="space-y-3"><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();onChange('');setLoading(true);setError('');setData(null);setSearch(query);setPage(1);setRequestVersion(v=>v+1)}}><label className="min-w-0 flex-1">Find a conversation<Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email or subject"/></label><Button variant="outline" disabled={disabled||loading} className="self-end">Search conversations</Button></form>{error&&<p role="alert">{error}</p>}<label className="block">Inbox conversation<select className="block w-full rounded border bg-background p-2" value={value} disabled={disabled||loading} onChange={e=>onChange(e.target.value)}><option value="">{loading?'Loading conversations…':'Choose a conversation'}</option>{data?.threads.map(t=><option key={t.id} value={t.id}>{t.participantName||t.participantEmail} · {t.subject||'No subject'}</option>)}</select></label>{data?.threads.length===0&&<p>No active conversations match this search.</p>}<div className="flex flex-wrap gap-3"><Button variant="outline" disabled={loading||page<=1} onClick={()=>{onChange('');setLoading(true);setError('');setData(null);setPage(page-1)}}>Previous conversations</Button><Button variant="outline" disabled={loading||!data||page>=data.pagination.totalPages} onClick={()=>{onChange('');setLoading(true);setError('');setData(null);setPage(page+1)}}>More conversations</Button><Link className="self-center underline" href={value?`/inbox?thread=${value}`:'/inbox'}>Open inbox / take over</Link></div></div>
}
