import '@testing-library/jest-dom/vitest'
import {it,expect,vi} from 'vitest'
import {render,screen,fireEvent,waitFor,act} from '@testing-library/react'
import {LeadsContent} from '@/app/(dashboard)/leads/leads-content'
it('edits current lead details with narrow PATCH and keeps email read-only',async()=>{const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>new Response(JSON.stringify(init?{saved:true}:String(input).includes('/lists')?{lists:[]}:{leads:[{id:'lead-1',email:'ada@example.test',first_name:'Ada',last_name:'Lovelace',phone:'+14155550000',company:'Old company',title:'Director',status:'active',created_at:'2026-10-05'}],pagination:{total:1,totalPages:1}})));vi.stubGlobal('fetch',fetcher);render(<LeadsContent/>);await screen.findByText('ada@example.test');fireEvent.pointerDown(screen.getByRole('button',{name:'Actions for ada@example.test'}),{button:0,ctrlKey:false,pointerType:'mouse'});fireEvent.click(await screen.findByRole('menuitem',{name:'Edit'}));expect(screen.getByLabelText('Email *')).toHaveAttribute('readOnly');expect(screen.getByLabelText('Phone')).toHaveValue('+14155550000');fireEvent.change(screen.getByLabelText('Company'),{target:{value:'New company'}});fireEvent.click(screen.getByRole('button',{name:'Save lead changes'}));await waitFor(()=>expect(fetcher.mock.calls.some(([url,init])=>String(url)==='/api/leads/lead-1'&&init?.method==='PATCH')).toBe(true));const body=JSON.parse(String(fetcher.mock.calls.find(([,init])=>init?.method==='PATCH')?.[1]?.body));expect(body).toEqual({firstName:'Ada',lastName:'Lovelace',company:'New company',title:'Director'});vi.unstubAllGlobals()})
it('keeps rejected edits visible and does not invent success',async()=>{vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>new Response(JSON.stringify(init?{error:'Only owners can update this lead'}:String(input).includes('/lists')?{lists:[]}:{leads:[{id:'lead-1',email:'ada@example.test',first_name:'Ada',status:'active',created_at:'2026-10-05'}],pagination:{total:1,totalPages:1}}),{status:init?403:200})));render(<LeadsContent/>);await screen.findByText('ada@example.test');fireEvent.pointerDown(screen.getByRole('button',{name:'Actions for ada@example.test'}),{button:0,ctrlKey:false,pointerType:'mouse'});fireEvent.click(await screen.findByRole('menuitem',{name:'Edit'}));fireEvent.click(screen.getByRole('button',{name:'Save lead changes'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Save lead changes'})).not.toBeDisabled());expect(screen.getByRole('dialog')).toBeVisible();vi.unstubAllGlobals()})
it('imports quoted CSV through the existing endpoint preserving fields',async()=>{const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>new Response(JSON.stringify(init?{imported:1,updated:0,skipped:0,errors:[]}:String(input).includes('/lists')?{lists:[]}:{leads:[],pagination:{total:0,totalPages:0}})));vi.stubGlobal('fetch',fetcher);const {container}=render(<LeadsContent/>);const file=new File(['email,company,title\na@example.test,"Example, Inc.","Director\nSales"'],'leads.csv',{type:'text/csv'});Object.defineProperty(file,'text',{value:async()=> 'email,company,title\na@example.test,"Example, Inc.","Director\nSales"'});fireEvent.change(container.querySelector('input[type="file"]')!,{target:{files:[file]}});await waitFor(()=>expect(fetcher.mock.calls.some(([url,init])=>String(url)==='/api/leads/import'&&init?.method==='POST')).toBe(true));const body=JSON.parse(String(fetcher.mock.calls.find(([,init])=>init?.method==='POST')?.[1]?.body));expect(body.leads).toEqual([{email:'a@example.test',company:'Example, Inc.',title:'Director\nSales'}]);vi.unstubAllGlobals()})

it('late old edit response preserves a newly opened lead draft',async()=>{
 let finish:(r:Response)=>void=()=>{};let posted=false
 vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{
 if(init?.method==='PATCH'){posted=true;return new Promise<Response>(resolve=>{finish=resolve})}
 return Response.json(String(input).includes('/lists')?{lists:[]}:{leads:[{id:'lead-1',email:'ada@example.test',first_name:'Ada',status:'active',created_at:'2026-10-05'}],pagination:{total:1,totalPages:1}})
 }))
 render(<LeadsContent/>);await screen.findByText('ada@example.test')
 fireEvent.pointerDown(screen.getByRole('button',{name:'Actions for ada@example.test'}),{button:0,ctrlKey:false,pointerType:'mouse'});fireEvent.click(await screen.findByRole('menuitem',{name:'Edit'}))
 fireEvent.click(screen.getByRole('button',{name:'Save lead changes'}));await waitFor(()=>expect(posted).toBe(true))
 fireEvent.click(screen.getByRole('button',{name:'Cancel'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull())
 fireEvent.click(screen.getByRole('button',{name:'Add Lead'}));fireEvent.change(screen.getByLabelText('Company'),{target:{value:'Unsaved next company'}})
 await act(async()=>{finish(Response.json({saved:true}));await new Promise(resolve=>setTimeout(resolve,10))})
 expect(screen.getByRole('dialog')).toBeVisible();expect(screen.getByLabelText('Company')).toHaveValue('Unsaved next company');vi.unstubAllGlobals()
})

it('shows the server row failure so the operator can correct the import',async()=>{
 const rowError='Failed to import bad@example.test: contact field rejected'
 vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>Response.json(init?.method==='POST'?{imported:1,updated:0,skipped:0,errors:[rowError]}:String(input).includes('/lists')?{lists:[]}:{leads:[],pagination:{total:0,totalPages:0}})))
 const {container}=render(<LeadsContent/>);const text='email,company\ngood@example.test,Good\nbad@example.test,Bad';const file=new File([text],'leads.csv',{type:'text/csv'});Object.defineProperty(file,'text',{value:async()=>text})
 fireEvent.change(container.querySelector('input[type="file"]')!,{target:{files:[file]}})
 expect(await screen.findByText(rowError)).toBeVisible();expect(screen.getByRole('region',{name:'CSV import result'})).toHaveTextContent('Imported 1; updated 0; server skipped 0; locally skipped 0');vi.unstubAllGlobals()
})

it('old edit finally cannot enable Send while a newer create request is pending',async()=>{
 let finishOld:(response:Response)=>void=()=>{},finishNew:(response:Response)=>void=()=>{}
 const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{if(init?.method==='PATCH')return new Promise<Response>(resolve=>{finishOld=resolve});if(init?.method==='POST')return new Promise<Response>(resolve=>{finishNew=resolve});return Response.json(String(input).includes('/lists')?{lists:[]}:{leads:[{id:'lead-1',email:'ada@example.test',first_name:'Ada',status:'active',created_at:'2026-10-05'}],pagination:{total:1,totalPages:1}})});vi.stubGlobal('fetch',fetcher)
 render(<LeadsContent/>);await screen.findByText('ada@example.test');fireEvent.pointerDown(screen.getByRole('button',{name:'Actions for ada@example.test'}),{button:0,ctrlKey:false,pointerType:'mouse'});fireEvent.click(await screen.findByRole('menuitem',{name:'Edit'}));fireEvent.click(screen.getByRole('button',{name:'Save lead changes'}));await waitFor(()=>expect(fetcher.mock.calls.some(([,init])=>init?.method==='PATCH')).toBe(true))
 fireEvent.click(screen.getByRole('button',{name:'Cancel'}));fireEvent.click(screen.getByRole('button',{name:'Add Lead'}));fireEvent.change(screen.getByLabelText('Email *'),{target:{value:'new@example.test'}});fireEvent.change(screen.getByLabelText('Company'),{target:{value:'Pending newer company'}});fireEvent.click(screen.getAllByRole('button',{name:'Add Lead'}).at(-1)!);await waitFor(()=>expect(fetcher.mock.calls.some(([,init])=>init?.method==='POST')).toBe(true))
 await act(async()=>{finishOld(Response.json({saved:true}));await Promise.resolve()});expect(screen.getByRole('button',{name:'Saving...'})).toBeDisabled();expect(screen.getByLabelText('Company')).toHaveValue('Pending newer company')
 await act(async()=>{finishNew(Response.json({error:'Correct this new lead'},{status:400}));await Promise.resolve()});await waitFor(()=>expect(screen.queryByRole('button',{name:'Saving...'})).toBeNull());expect(screen.getByRole('dialog')).toBeVisible();expect(screen.getByLabelText('Company')).toHaveValue('Pending newer company');vi.unstubAllGlobals()
})
it('reports local invalid-email records alongside exact server summary',async()=>{
 vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>Response.json(init?.method==='POST'?{imported:1,updated:0,skipped:1,errors:[]}:String(input).includes('/lists')?{lists:[]}:{leads:[],pagination:{total:0,totalPages:0}})))
 const {container}=render(<LeadsContent/>);const text='email,company\ngood@example.test,Good\nother@example.test,Other\nbad-email,Bad';const file=new File([text],'leads.csv',{type:'text/csv'});Object.defineProperty(file,'text',{value:async()=>text});const input=container.querySelector('input[type="file"]');if(!input)throw Error('Missing CSV input');fireEvent.change(input,{target:{files:[file]}})
 expect(await screen.findByText('CSV record 4: bad-email — Email address is invalid')).toBeVisible();expect(screen.getByRole('region',{name:'CSV import result'})).toHaveTextContent('Imported 1; updated 0; server skipped 1; locally skipped 1');vi.unstubAllGlobals()
})
it('creates a lead with an explicitly entered phone through existing API fields only',async()=>{
 const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>Response.json(init?.method==='POST'?{saved:true}:String(input).includes('/lists')?{lists:[]}:{leads:[],pagination:{total:0,totalPages:0}}));vi.stubGlobal('fetch',fetcher)
 render(<LeadsContent/>);fireEvent.click(screen.getByRole('button',{name:'Add Lead'}));fireEvent.change(screen.getByLabelText('Email *'),{target:{value:'phone@example.test'}});fireEvent.change(screen.getByLabelText('Phone'),{target:{value:'+14155552671'}});fireEvent.click(screen.getAllByRole('button',{name:'Add Lead'}).at(-1)!);await waitFor(()=>expect(fetcher.mock.calls.some(([,init])=>init?.method==='POST')).toBe(true))
 const body=JSON.parse(String(fetcher.mock.calls.find(([,init])=>init?.method==='POST')?.[1]?.body));expect(body).toEqual({email:'phone@example.test',firstName:'',lastName:'',company:'',title:'',phone:'+14155552671'});vi.unstubAllGlobals()
})
it('imports an optional CSV phone without adding consent or unsupported fields',async()=>{
 const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>Response.json(init?.method==='POST'?{imported:1,updated:0,skipped:0,errors:[]}:String(input).includes('/lists')?{lists:[]}:{leads:[],pagination:{total:0,totalPages:0}}));vi.stubGlobal('fetch',fetcher)
 const {container}=render(<LeadsContent/>);const text='email,phone_number\nphone@example.test,+14155552671';const file=new File([text],'phone.csv',{type:'text/csv'});Object.defineProperty(file,'text',{value:async()=>text});const input=container.querySelector('input[type="file"]');if(!input)throw Error('Missing CSV input');fireEvent.change(input,{target:{files:[file]}})
 await waitFor(()=>expect(fetcher.mock.calls.some(([,init])=>init?.method==='POST')).toBe(true));expect(JSON.parse(String(fetcher.mock.calls.find(([,init])=>init?.method==='POST')?.[1]?.body)).leads).toEqual([{email:'phone@example.test',phone:'+14155552671'}]);vi.unstubAllGlobals()
})
it('updates an explicitly edited phone while preserving the read-only email contract',async()=>{
 const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>Response.json(init?.method==='PATCH'?{saved:true}:String(input).includes('/lists')?{lists:[]}:{leads:[{id:'lead-1',email:'ada@example.test',first_name:'Ada',phone:'+14155550000',status:'active',created_at:'2026-10-05'}],pagination:{total:1,totalPages:1}}));vi.stubGlobal('fetch',fetcher);render(<LeadsContent/>);await screen.findByText('ada@example.test');fireEvent.pointerDown(screen.getByRole('button',{name:'Actions for ada@example.test'}),{button:0,ctrlKey:false,pointerType:'mouse'});fireEvent.click(await screen.findByRole('menuitem',{name:'Edit'}));fireEvent.change(screen.getByLabelText('Phone'),{target:{value:'+14155552671'}});fireEvent.click(screen.getByRole('button',{name:'Save lead changes'}));await waitFor(()=>expect(fetcher.mock.calls.some(([,init])=>init?.method==='PATCH')).toBe(true));expect(JSON.parse(String(fetcher.mock.calls.find(([,init])=>init?.method==='PATCH')?.[1]?.body))).toEqual({firstName:'Ada',lastName:'',company:'',title:'',phone:'+14155552671'});vi.unstubAllGlobals()
})
