import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { WinnrDashboard } from '@/components/winnr/winnr-dashboard'

const connection = { id: 'connection-1', version: 1, account: { id: 'a', name: 'Operations', permissions: ['read', 'write'], plan: null, universalInboxEnabled: true }, connectedAt: '2026-10-05T12:00:00Z', verifiedAt: '2026-10-05T12:00:00Z' }
const page = { items: [{ id: 'm1', email: 'hello@example.com', name: null, status: 'active', dailyLimit: null }], observedAt: '2026-10-05T12:00:00Z', connectionId: connection.id, connectionVersion: 1, hasMore: false, nextCursor: null }
const reply = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status })
function mockApi(manager = true) {
  const mock = vi.fn(async (url: string, init?: RequestInit) => {
    if (url.includes('/connection')) return reply({ connection, canManage: manager })
    if (init?.method === 'POST') return reply({ operation: { id: 'op', status: 'succeeded' } })
    return reply(page)
  })
  vi.stubGlobal('fetch', mock)
  return mock
}
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
describe('Winnr operator controls', () => {
  it('loads only the active mailbox tab and preserves unknown values', async () => {
    const api = mockApi()
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    expect(screen.getAllByText(/Unknown/).length).toBeGreaterThan(0)
    expect(api.mock.calls.map(c => c[0]).some(u => u.includes('/warming'))).toBe(false)
  })
  it('gates all mutations by organization role', async () => {
    mockApi(false)
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    expect(screen.queryByRole('button', { name: 'Enable warming' })).not.toBeInTheDocument()
    expect(screen.queryByLabelText('API token')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Disconnect account' })).not.toBeInTheDocument()
  })
  it('requires explicit paid consent and submits once for a double click', async () => {
    const api = mockApi()
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    fireEvent.click(screen.getByRole('button', { name: 'Enable warming' }))
    const confirm = screen.getByRole('button', { name: 'Confirm enable' })
    expect(confirm).toBeDisabled()
    fireEvent.click(screen.getByRole('checkbox'))
    fireEvent.click(confirm); fireEvent.click(confirm)
    await waitFor(() => expect(api.mock.calls.filter(c => c[1]?.method === 'POST')).toHaveLength(1))
    const body = JSON.parse(String(api.mock.calls.find(c => c[1]?.method === 'POST')?.[1]?.body))
    expect(body).toMatchObject({ action: 'enable', confirmPaid: true, connectionId: connection.id, connectionVersion: 1, mailboxIds: ['m1'] })
    await waitFor(() => expect(api.mock.calls.filter(c => c[0].includes('/mailboxes')).length).toBe(2))
  })
  it('holds an uncertain operation and never automatically retries', async () => {
    const api = mockApi()
    api.mockImplementation(async (url, init) => init?.method === 'POST' ? reply({ error: { code: 'outcome_unknown', message: 'Uncertain', outcomeUnknown: true, operationId: 'op-123' } }, 409) : reply(url.includes('connection') ? { connection, canManage: true } : page))
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    fireEvent.click(screen.getByRole('button', { name: 'Enable warming' }))
    fireEvent.click(screen.getByRole('checkbox'))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm enable' }))
    await screen.findAllByText(/op-123/)
    expect(screen.getByRole('button', { name: 'Enable warming' })).toBeDisabled()
    expect(api.mock.calls.filter(c => c[1]?.method === 'POST')).toHaveLength(1)
  })
  it('never labels a failed connection read disconnected', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => reply({ error: { code: 'provider_error', message: 'Provider unavailable' } }, 503)))
    render(<WinnrDashboard />)
    await screen.findByText('Provider unavailable')
    expect(screen.queryByText('No account connected')).not.toBeInTheDocument()
  })
  it('keeps the token in a password field, submits the version guard and clears only after success', async () => {
    const api = mockApi()
    const storage = vi.spyOn(Storage.prototype, 'setItem')
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    const field = screen.getByLabelText('API token')
    expect(field).toHaveAttribute('type', 'password')
    fireEvent.change(field, { target: { value: 'private-token' } })
    api.mockImplementationOnce(async () => reply({ error: { code: 'invalid_token', message: 'Invalid token' } }, 400))
    fireEvent.click(screen.getByRole('button', { name: 'Replace connection' }))
    await screen.findByText('Invalid token')
    expect(field).toHaveValue('private-token')
    fireEvent.click(screen.getByRole('button', { name: 'Replace connection' }))
    await waitFor(() => expect(field).toHaveValue(''))
    const body = JSON.parse(String(api.mock.calls.find(c => c[1]?.method === 'POST')?.[1]?.body))
    expect(body).toEqual({ token: 'private-token', expectedConnectionId: connection.id, expectedVersion: 1 })
    expect(storage).not.toHaveBeenCalled()
    storage.mockRestore()
  })
  it('blocks warming but permits owner disconnect with a read-only token', async () => {
    const api = mockApi()
    api.mockImplementation(async (url, init) => reply(init?.method === 'DELETE' ? { connection: null, canManage: true } : url.includes('connection') ? { connection: { ...connection, account: { ...connection.account, permissions: ['read'] } }, canManage: true } : page))
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    expect(screen.queryByRole('button', { name: 'Enable warming' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Disconnect account' }))
    expect(screen.getByText(/does not stop warming or cancel Winnr billing/)).toBeInTheDocument()
    expect(api.mock.calls.some(c => c[1]?.method === 'DELETE')).toBe(false)
    fireEvent.click(screen.getByRole('button', { name: 'Confirm disconnect' }))
    await screen.findByText('No account connected')
    expect(api.mock.calls.filter(c => c[1]?.method === 'DELETE')).toHaveLength(1)
  })
  it('uses bounded cursor pagination with a working previous page', async () => {
    const api = mockApi()
    api.mockImplementation(async url => reply(url.includes('connection') ? { connection, canManage: true } : url.includes('cursor=next') ? { ...page, items: [{ ...page.items[0], email: 'second@example.com' }] } : { ...page, nextCursor: 'next', hasMore: true }))
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await screen.findByText('second@example.com')
    expect(api.mock.calls.some(c => c[0] === '/api/winnr/mailboxes?limit=25&cursor=next')).toBe(true)
    fireEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await screen.findByText('hello@example.com')
  })
  it('discards stale responses after switching tabs even if transport ignores abort', async () => {
    const api = mockApi()
    let resolvePage: (value: Response) => void = () => { throw new Error('No pending read') }
    api.mockImplementation(async url => url.includes('connection') ? reply({ connection, canManage: true }) : url.includes('mailboxes') ? new Promise<Response>(resolve => { resolvePage = resolve }) : reply({ ...page, items: [{ id: 'd', name: 'example.com', status: 'active', dnsHealth: null, checkedAt: null }] }))
    render(<WinnrDashboard />)
    await screen.findByRole('tab', { name: 'Domains' })
    fireEvent.click(screen.getByRole('tab', { name: 'Domains' }))
    await screen.findByText('example.com')
    resolvePage(reply(page))
    await waitFor(() => expect(screen.queryByText('hello@example.com')).not.toBeInTheDocument())
  })
  it('rejects observations belonging to another connection version', async () => {
    const api = mockApi()
    api.mockImplementation(async url => reply(url.includes('connection') ? { connection, canManage: true } : { ...page, connectionVersion: 2 }))
    render(<WinnrDashboard />)
    await screen.findByText(/account changed during this read/)
    expect(screen.queryByText('hello@example.com')).not.toBeInTheDocument()
  })
  it('holds network failures using the submitted operation reference', async () => {
    const api = mockApi()
    api.mockImplementation(async (url, init) => {
      if (init?.method === 'POST') throw new TypeError('Network unavailable')
      return reply(url.includes('connection') ? { connection, canManage: true } : page)
    })
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    fireEvent.click(screen.getByRole('button', { name: 'Enable warming' }))
    fireEvent.click(screen.getByRole('checkbox'))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm enable' }))
    await screen.findByText(/Outcome unknown/)
    const body = JSON.parse(String(api.mock.calls.find(c => c[1]?.method === 'POST')?.[1]?.body))
    expect(screen.getByText(/Reconciliation required:/)).toHaveTextContent(body.operationId)
    fireEvent.click(screen.getByRole('button', { name: 'Refresh view' }))
    await screen.findByText('hello@example.com')
    expect(screen.getByRole('button', { name: 'Enable warming' })).toBeDisabled()
    expect(api.mock.calls.filter(c => c[1]?.method === 'POST')).toHaveLength(1)
  })

  it('uses bounded warming pages and refreshes the actual provider state after pause', async () => {
    const api = mockApi()
    let status = 'active'
    api.mockImplementation(async (url, init) => {
      if (init?.method === 'POST') { status = 'paused'; return reply({ operation: { id: 'op', status: 'succeeded' } }) }
      return reply(url.includes('connection') ? { connection, canManage: true } : url.includes('/warming') ? { ...page, items: [{ id: 'm1', email: 'warming@example.com', status, healthScore: null, sent: null, replies: null, lastSyncedAt: null }], page: 1, perPage: 25, total: null, hasMore: true } : page)
    })
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    fireEvent.click(screen.getByRole('tab', { name: 'Warming' }))
    await screen.findByText('warming@example.com')
    expect(screen.getByText(/Total: Unknown/)).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Pause warming' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm pause' }))
    await screen.findByRole('button', { name: 'Resume warming' })
    expect(screen.getByText('Provider state: paused')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
    await waitFor(() => expect(api.mock.calls.some(c => c[0] === '/api/winnr/warming?page=2&perPage=25')).toBe(true))
  })
  it('renders inbox content as plain text and has no send action', async () => {
    const api = mockApi()
    api.mockImplementation(async url => reply(url.includes('connection') ? { connection, canManage: true } : url.includes('/inbox') ? { ...page, items: [{ id: 'i', subject: 'Reply', preview: '<img src=x onerror=alert(1)>', from: 'from@example.com', to: 'to@example.com', receivedAt: '2026-10-05T12:00:00Z' }] } : page))
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    fireEvent.click(screen.getByRole('tab', { name: 'Inbox' }))
    await screen.findByText('<img src=x onerror=alert(1)>')
    expect(document.querySelector('img')).toBeNull()
    expect(screen.queryByRole('button', { name: /send/i })).not.toBeInTheDocument()
  })
  it('confirms disconnect with a billing warning and uses the expected connection guard', async () => {
    const api = mockApi()
    api.mockImplementation(async (url, init) => reply(init?.method === 'DELETE' ? { connection: null, canManage: true } : url.includes('connection') ? { connection, canManage: true } : page))
    render(<WinnrDashboard />)
    await screen.findByText('hello@example.com')
    fireEvent.click(screen.getByRole('button', { name: 'Disconnect account' }))
    expect(screen.getByText(/does not stop warming or cancel Winnr billing/)).toBeInTheDocument()
    expect(api.mock.calls.some(c => c[1]?.method === 'DELETE')).toBe(false)
    fireEvent.click(screen.getByRole('button', { name: 'Confirm disconnect' }))
    await screen.findByText('No account connected')
    expect(JSON.parse(String(api.mock.calls.find(c => c[1]?.method === 'DELETE')?.[1]?.body))).toEqual({ expectedConnectionId: connection.id, expectedVersion: 1 })
  })
  it('shows provider list errors without an empty-state claim', async () => {
    const api = mockApi()
    api.mockImplementation(async url => url.includes('connection') ? reply({ connection, canManage: true }) : reply({ error: { code: 'provider_error', message: 'Mailbox read unavailable' } }, 503))
    render(<WinnrDashboard />)
    await screen.findByText('Mailbox read unavailable')
    expect(screen.queryByText(/No mailboxes returned/)).not.toBeInTheDocument()
  })

})
