import { describe,it,expect,vi,beforeEach } from 'vitest'
import { dispatchCampaign,renderDispatchMessage,configurationSchema,candidateSchema,fingerprintDispatchMessage,type DispatchSendInput } from '@/lib/outreach/dispatch'
import { fingerprintWinnrSmtpMessage } from '@/lib/winnr/smtp-transport'
const org='11111111-1111-4111-8111-111111111111',campaign='22222222-2222-4222-8222-222222222222',lead='33333333-3333-4333-8333-333333333333',connection='44444444-4444-4444-8444-444444444444',attempt='55555555-5555-4555-8555-555555555555',claim='66666666-6666-4666-8666-666666666666'
const candidate=candidateSchema.parse({enrollmentId:lead,lead:{id:lead,email:'lead@example.com',first_name:'A <B>',last_name:'Person',company:'Customer',title:'Owner'},step:{id:lead,campaign_id:campaign,step_number:1,subject:'Hi {{first_name}}',body_text:'Hello {{company}}',body_html:'<p>Hello {{first_name}}</p>',delay_days:0,delay_hours:0,condition_type:'always',created_at:null,updated_at:null},configuration:{campaign_id:campaign,organization_id:org,sender_name:'Approved name',sender_company:'Approved company',business_address:'Approved supplied address',sender_email:'sender@example.com',mailbox_id:'mailbox',mailbox_daily_limit:5,connection_id:connection,connection_version:1,killed:false}})
beforeEach(()=>vi.stubEnv('ENCRYPTION_SECRET','synthetic-only-fixture-secret'))
describe('immutable dispatch orchestration',()=>{
 it('renders escaped real values, real identity and signed opt-out before reserving',()=>{const message=renderDispatchMessage(candidate,'https://fixture.example');expect(message.subject).toBe('Hi A <B>');expect(message.html).toContain('A &lt;B&gt;');expect(message.text).toContain(candidate.configuration.business_address);expect(message.headers?.['List-Unsubscribe-Post']).toBe('List-Unsubscribe=One-Click');expect(fingerprintDispatchMessage(message)).toBe(fingerprintWinnrSmtpMessage(message))})
 it('blocks unsupported variables, conditions and absent identity',()=>{expect(()=>renderDispatchMessage({...candidate,step:{...candidate.step,subject:'{{unsupported}}'}},'https://fixture.example')).toThrow();expect(()=>renderDispatchMessage({...candidate,step:{...candidate.step,condition_type:'not_clicked'}},'https://fixture.example')).toThrow();expect(configurationSchema.safeParse({...candidate.configuration,business_address:''}).success).toBe(false)})
 it('never invokes SMTP without a durable reservation',async()=>{const call=vi.fn().mockResolvedValueOnce({ready:true,candidates:[candidate]}).mockResolvedValueOnce({allowed:false,reason:'duplicate_touch'}),send=vi.fn();await dispatchCampaign('actor',org,campaign,1,{repository:{call},transport:{send},mailboxAvailable:async()=>true,appUrl:'https://fixture.example'});expect(send).not.toHaveBeenCalled()})
 it('returns acceptance receipt for reconciliation after persistence failure without resending',async()=>{const call=vi.fn().mockResolvedValueOnce({ready:true,candidates:[candidate]}).mockResolvedValueOnce({allowed:true,attempt:{id:attempt,claim_token:claim}}).mockRejectedValueOnce(new Error('DB offline'));const send=vi.fn(async(input:DispatchSendInput)=>({outcome:'accepted' as const,messageId:input.message.messageId,recipient:input.message.to}));const result=await dispatchCampaign('actor',org,campaign,1,{repository:{call},transport:{send},mailboxAvailable:async()=>true,appUrl:'https://fixture.example'});expect(send).toHaveBeenCalledTimes(1);expect(result.outcomes[0]).toMatchObject({outcome:'unknown',code:'receipt_persistence_failed',receipt:{outcome:'accepted',recipient:'lead@example.com'}})})
 it('network exceptions settle as unknown without another SMTP attempt',async()=>{const call=vi.fn().mockResolvedValueOnce({ready:true,candidates:[candidate]}).mockResolvedValueOnce({allowed:true,attempt:{id:attempt,claim_token:claim}}).mockResolvedValueOnce({settled:true,status:'unknown'});const send=vi.fn().mockRejectedValue(new Error('network'));await dispatchCampaign('actor',org,campaign,1,{repository:{call},transport:{send},mailboxAvailable:async()=>true,appUrl:'https://fixture.example'});expect(send).toHaveBeenCalledTimes(1);expect(call).toHaveBeenLastCalledWith('actor',org,'settle',expect.objectContaining({outcome:'unknown'}))})
 it('does not reserve when current provider availability is unknown',async()=>{const call=vi.fn().mockResolvedValueOnce({ready:true,candidates:[candidate]});const send=vi.fn();await dispatchCampaign('actor',org,campaign,1,{repository:{call},transport:{send},mailboxAvailable:async()=>false,appUrl:'https://fixture.example'});expect(call).toHaveBeenCalledTimes(1);expect(send).not.toHaveBeenCalled()})
})
