import { it, expect, vi, beforeEach } from 'vitest';
import { NextRequest } from 'next/server';
const mocks = vi.hoisted(() => ({ auth: vi.fn(), origin: vi.fn(), call: vi.fn(),factory:vi.fn() }));
vi.mock('@/app/api/winnr/_shared', () => ({ resolveAuthContext: mocks.auth, assertSameOrigin: mocks.origin, winnrErrorResponse: () => new Response(JSON.stringify({ error: 'Rejected' }), { status: 403 }) }));
vi.mock('@/lib/outreach/agents/database', () => ({ createAgentRepository: mocks.factory }));
import { POST } from '@/app/api/outreach/agents/route';
beforeEach(() => { vi.clearAllMocks();mocks.origin.mockImplementation(()=>undefined);mocks.factory.mockReturnValue({call:mocks.call}); mocks.auth.mockResolvedValue({ userId: '11111111-1111-4111-8111-111111111111', organizationId: '11111111-1111-4111-8111-111111111111', role: 'member' }); });
it('refuses member configuration before privileged repository access', async () => { const r = await POST(new NextRequest('https://example.test/api/outreach/agents', { method: 'POST', body: JSON.stringify({ action: 'model', model: 'test', expectedRevision: 0, apiKey: 'synthetic-key' }) })); expect(r.status).toBe(403); expect(mocks.call).not.toHaveBeenCalled(); });
it('refuses cross-origin request before privileged access', async () => { mocks.auth.mockResolvedValue({ userId: 'id', organizationId: 'org', role: 'owner' }); mocks.origin.mockImplementation(() => { throw Error('Origin'); }); const r = await POST(new NextRequest('https://example.test/api/outreach/agents', { method: 'POST', body: '{}' })); expect(r.status).toBe(403); expect(mocks.call).not.toHaveBeenCalled(); });

it('captures absolute budget before cookie authentication consumes time',async()=>{vi.useFakeTimers({toFake:['Date']});const now=Date.now();mocks.auth.mockImplementation(async()=>{vi.setSystemTime(now+5000);return{userId:'11111111-1111-4111-8111-111111111111',organizationId:'11111111-1111-4111-8111-111111111111',role:'owner'}});mocks.call.mockResolvedValue({saved:true});try{const result=await POST(new NextRequest('https://example.test/api/outreach/agents',{method:'POST',body:JSON.stringify({action:'policy',campaignId:'11111111-1111-4111-8111-111111111111',expectedRevision:0,policy:{enabled:false}})}));expect(result.status).toBe(200);expect(mocks.factory).toHaveBeenCalledWith(now+30000);expect(mocks.call.mock.calls[0]?.[4]).toBe(now+30000)}finally{vi.useRealTimers()}})
