import {createHash} from 'node:crypto';
import { describe, it, expect, vi } from 'vitest';
import type { AgentRepository } from '@/lib/outreach/agents/database';
import { runCopy, saveManualDraft, classifyReply } from '@/lib/outreach/agents/service';
const brief = { audience: 'Owners', problem: 'Slow follow up', offer: 'Email setup', tone: 'plain', cta: 'Would a demo help?', exclusions: [], claims: [], faqs: [] };
const policy = { enabled: false, allowedIntents: ['question'], minConfidence: .95, maxReplies: 1, dailyCalls: 20, startHour: 9, endHour: 17 };
const id = '11111111-1111-4111-8111-111111111111';
function fixture() { const log: string[] = []; return { log, repo: { call: vi.fn<AgentRepository['call']>(async (_a: string, _o: string, action: string) => { log.push(action); return action === 'read' ? { model: { revision: 1, model: 'explicit-model', configured: true }, briefs: [{ campaign_id: id, revision: 1, brief }], policies: [{ campaign_id: id, revision: 1, policy }], drafts: [], runs: [], decisions: [] } : action === 'reserve' ? { allowed: true, runId: id, model: 'explicit-model', brief, briefRevision: 1, policy, policyRevision: 1 } : { saved: true }; }), key: vi.fn(async () => 'fake-key') }, model: { generate: vi.fn(async () => { log.push('paid'); return { output: { subject: 'Email setup', body: 'Email setup. Would a demo help?', claimIds: [] }, servedModel: 'fixture-served-model' }; }) } }; }
describe('durable model-run boundary', () => {
    it('reserves before paid work and saves only validated draft text', async () => { const f = fixture(); const result = await runCopy({ userId: id, organizationId: id, role: 'owner' }, id, f.repo, f.model); expect(result).toHaveProperty('status', 'draft'); expect(f.log).toEqual(['read', 'reserve', 'paid', 'finish']); });
    it('holds unknown model outcome with redacted error and never retries', async () => { const f = fixture(); f.model.generate.mockRejectedValue(new Error('secret-key upstream error')); expect(await runCopy({ userId: id, organizationId: id, role: 'owner' }, id, f.repo, f.model)).toMatchObject({ status: 'unknown' }); expect(f.model.generate).toHaveBeenCalledTimes(1); expect(JSON.stringify(f.repo.call.mock.calls)).not.toContain('secret-key'); });
    it('rejects members before repository or paid calls', async () => { const f = fixture(); await expect(runCopy({ userId: id, organizationId: id, role: 'member' }, id, f.repo, f.model)).rejects.toThrow(); expect(f.log).toEqual([]); });
    it('saves a manually reviewed draft with no configured AI key or model call', async () => { const f = fixture(); f.repo.call.mockImplementation(async (_a, _o, action) => { f.log.push(action); return action === 'read' ? { model: null, briefs: [{ campaign_id: id, revision: 1, brief }], policies: [], drafts: [], runs: [], decisions: [] } : { runId: id }; }); const result = await saveManualDraft({ userId: id, organizationId: id, role: 'owner' }, id, { subject: 'Email setup', body: 'Email setup. Would a demo help?', claimIds: [] }, f.repo); expect(result.status).toBe('draft'); expect(f.log).toEqual(['read', 'manualDraft']); expect(f.model.generate).not.toHaveBeenCalled(); });
});

it('resumes a completed classification after decision persistence interruption without a second paid call',async()=>{const f=fixture();f.repo.call.mockImplementation(async(_a,_o,action)=>action==='conversation'?{campaignId:id,sourceReplyId:id,controlRevision:1,mode:'assist',body:'What is the price?',bodyHash:createHash('sha256').update('What is the price?').digest('hex'),brief,briefRevision:1,policy,policyRevision:1}:{allowed:false,status:'succeeded',sourceBodyHash:createHash('sha256').update('What is the price?').digest('hex'),runId:id,result:{intent:'question',confidence:.99,reason:'Price question',templateId:null,source:'model',model:'fixture-served-model'}});const r=await classifyReply({userId:id,organizationId:id,role:'owner'},id,f.repo,f.model);expect(r).toHaveProperty('classification.intent','question');expect(r.modelCalls).toBe(0);expect(f.model.generate).not.toHaveBeenCalled()})
