import { describe,expect,it,vi } from 'vitest'
import { configureIngestion,hydrateIngestedMessage,ingestionCallbackUrl,processWinnrIngestionReceipt,syncIngestion,type IngestionServiceDeps } from '@/lib/outreach/ingestion-service'
const org='11111111-1111-4111-8111-111111111111',conn='22222222-2222-4222-8222-222222222222',endpoint='33333333-3333-4333-8333-333333333333',messageId='44444444-4444-4444-8444-444444444444',account='55555555-5555-4555-8555-555555555555'
const actor={userId:'owner',organizationId:org,role:'owner' as const}
const connection={id:conn,organizationId:org,version:1,providerAccountId:'acct_own',accountName:'Fixture',accountPlan:null,permissions:['read','write'],universalInboxEnabled:true,connectedAt:'2026-10-05T00:00:00Z',verifiedAt:'2026-10-05T00:00:00Z'}
const row={uid:'123',message_id:'<reply@example.test>',mailbox:'sender@example.test',from:'lead@example.test',to:'sender@example.test',received_at:'2026-10-05T00:00:00Z',subject:'Reply'}
const message={id:messageId,organization_id:org,connection_id:conn,connection_version:1,provider_account_id:'acct_own',account_id:account,mailbox_id:'provider-1',message_id:row.message_id,in_reply_to:'<provider@example.test>',from_email:row.from,to_email:row.mailbox,reply_id:messageId,body_status:'pending' as const}
function fakeDeps(){const provider={webhook:vi.fn(async()=>({id:'wh_one',url:ingestionCallbackUrl('https://app.example',endpoint),events:['email.received','message.relayed','email.bounced','email.complained'],status:'enabled' as const})),secret:vi.fn(async()=>({webhook_id:'wh_one',secret:'whsec_synthetic'})),mappings:vi.fn(async()=>[]),list:vi.fn(async()=>({data:[row],pagination:{has_more:false,cursor:null}})),body:vi.fn(async()=>({uid:row.uid,mailbox:row.mailbox,body:'unsubscribe'}))};const deps={repository:{endpoint:vi.fn(async()=>({id:endpoint,organizationId:org,connectionId:conn,connectionVersion:1,providerAccountId:'acct_own',secret:'whsec_synthetic'})),configuration:vi.fn(async()=>({endpointId:endpoint,configured:true,webhookId:'wh_one'})),prepare:vi.fn(async()=>({endpointId:endpoint,configured:true})),persist:vi.fn<IngestionServiceDeps['repository']['persist']>(async()=>({duplicate:false,eventId:messageId})),pending:vi.fn(async()=>[message]),pendingCount:vi.fn(async()=>0),messageForReceipt:vi.fn(async()=>message),saveBody:vi.fn(async()=>true),correlate:vi.fn(async()=>false)},connections:{getConnection:vi.fn(async()=>connection),getConnectionWithToken:vi.fn(async()=>({connection,token:'synthetic'}))},mailboxes:{status:vi.fn(async()=>[{providerMailboxId:'provider-1',email:row.mailbox,accountId:account,syncedAt:'2026-10-05T00:00:00Z'}])},provider:vi.fn(()=>provider)} satisfies IngestionServiceDeps;return{deps,provider}}
describe('ingestion provider processing and setup boundaries',()=>{
 it('refuses member/foreign mailbox before provider work',async()=>{const{deps}=fakeDeps();await expect(syncIngestion({...actor,role:'member'},{expectedConnectionId:conn,expectedConnectionVersion:1,mailboxId:'provider-1'},deps)).rejects.toThrow();expect(deps.provider).not.toHaveBeenCalled();await expect(syncIngestion(actor,{expectedConnectionId:conn,expectedConnectionVersion:1,mailboxId:'foreign'},deps)).rejects.toThrow();expect(deps.provider).not.toHaveBeenCalled()})
 it('persists body-pending receipt before body fetch failure and reports pending honestly',async()=>{const{deps,provider}=fakeDeps();provider.body.mockRejectedValue(new Error('private provider detail'));const result=await syncIngestion(actor,{expectedConnectionId:conn,expectedConnectionVersion:1,mailboxId:'provider-1'},deps);expect(deps.repository.persist).toHaveBeenCalledOnce();expect(deps.repository.persist.mock.invocationCallOrder[0]).toBeLessThan(provider.body.mock.invocationCallOrder[0]??0);expect(deps.repository.saveBody).not.toHaveBeenCalled();expect(result).toMatchObject({saved:1,hydrated:0,bodyUnavailable:1,bodyReady:false});expect(JSON.stringify(result)).not.toContain('private')})
 it('missing mapping does not prevent body retrieval; deterministic optout reaches atomic SQL port',async()=>{const{deps,provider}=fakeDeps();provider.mappings.mockRejectedValue(new Error('not rolled out'));expect((await syncIngestion(actor,{expectedConnectionId:conn,expectedConnectionVersion:1,mailboxId:'provider-1'},deps)).hydrated).toBe(1);expect(deps.repository.saveBody).toHaveBeenCalledWith(actor.userId,org,message.id,'123','unsubscribe',true,conn,1)})
 it('rejects cross-tenant hydration and mismatched body identity without persisting',async()=>{const{deps,provider}=fakeDeps();await expect(hydrateIngestedMessage({...actor,organizationId:'foreign'},message,row.uid,provider,deps.repository)).rejects.toThrow();expect(provider.body).not.toHaveBeenCalled();provider.body.mockResolvedValue({uid:'wrong',mailbox:row.mailbox,body:'secret text'});await expect(hydrateIngestedMessage(actor,message,row.uid,provider,deps.repository)).rejects.toThrow();expect(deps.repository.saveBody).not.toHaveBeenCalled()})
 it('prepares a callback without provider mutation; association validates endpoint before fetching secret',async()=>{const{deps,provider}=fakeDeps();const input={action:'prepare',expectedConnectionId:conn,expectedConnectionVersion:1};expect((await configureIngestion(actor,input,'https://app.example',deps)).callbackUrl).toBe(`https://app.example/api/winnr/webhooks/${endpoint}`);expect(deps.provider).not.toHaveBeenCalled();provider.webhook.mockResolvedValue({id:'wh_one',url:'https://foreign.example',events:['*'],status:'enabled'});await expect(configureIngestion(actor,{...input,action:'associate',webhookId:'wh_one'},'https://app.example',deps)).rejects.toThrow();expect(provider.secret).not.toHaveBeenCalled();expect(()=>ingestionCallbackUrl('http://localhost',endpoint)).toThrow()})
 it('worker port refuses missing provider message and never manufactures ready body',async()=>{const{deps,provider}=fakeDeps();provider.list.mockResolvedValue({data:[],pagination:{has_more:false,cursor:null}});expect(await processWinnrIngestionReceipt(actor,messageId,deps)).toMatchObject({bodyReady:false});expect(deps.repository.saveBody).not.toHaveBeenCalled()})
 it('stops further provider work once the absolute request deadline is exhausted',async()=>{const{deps,provider}=fakeDeps();await expect(processWinnrIngestionReceipt(actor,messageId,deps,Date.now()-1)).rejects.toMatchObject({code:'provider_error'});expect(deps.provider).not.toHaveBeenCalled();expect(provider.list).not.toHaveBeenCalled();expect(provider.body).not.toHaveBeenCalled()})
 it('reports bodies outside the current provider page as pending rather than ready',async()=>{const{deps}=fakeDeps();deps.repository.pendingCount.mockResolvedValue(12);expect(await syncIngestion(actor,{expectedConnectionId:conn,expectedConnectionVersion:1,mailboxId:'provider-1'},deps)).toMatchObject({hydrated:1,bodyPending:12,bodyReady:false})})

 it('recovers an old-version receipt through current mailbox ownership before saving its body',async()=>{
  const{deps,provider}=fakeDeps()
  deps.connections.getConnectionWithToken.mockResolvedValue({connection:{...connection,version:2},token:'synthetic'})
  deps.repository.endpoint.mockResolvedValue({id:endpoint,organizationId:org,connectionId:conn,connectionVersion:2,providerAccountId:'acct_own',secret:'whsec_synthetic'})
  deps.repository.messageForReceipt.mockResolvedValueOnce(message).mockResolvedValueOnce({...message,connection_version:2})
  expect(await processWinnrIngestionReceipt(actor,messageId,deps)).toEqual({bodyReady:true})
  expect(deps.repository.persist).toHaveBeenCalledOnce()
  expect(deps.repository.persist.mock.invocationCallOrder[0]).toBeLessThan(provider.body.mock.invocationCallOrder[0]??0)
  expect(deps.repository.saveBody).toHaveBeenCalledWith(actor.userId,org,messageId,'123','unsubscribe',true,conn,2)
 })
 it('uses distinct local receipt keys across connection rotation and exact historical pending count',async()=>{
  const{deps}=fakeDeps();const input={expectedConnectionId:conn,expectedConnectionVersion:1,mailboxId:'provider-1'}
  await syncIngestion(actor,input,deps)
  const first=deps.repository.persist.mock.calls[0]?.[1]
  deps.connections.getConnectionWithToken.mockResolvedValue({connection:{...connection,version:2},token:'synthetic'})
  deps.repository.endpoint.mockResolvedValue({id:endpoint,organizationId:org,connectionId:conn,connectionVersion:2,providerAccountId:'acct_own',secret:'whsec_synthetic'})
  await syncIngestion(actor,{...input,expectedConnectionVersion:2},deps)
  const second=deps.repository.persist.mock.calls[1]?.[1]
  expect(first?.id).not.toBe(second?.id)
  expect(deps.repository.pendingCount).toHaveBeenCalledWith(org,'acct_own',account)
 })

})
