import { beforeAll,beforeEach,describe,it,expect } from 'vitest'
import { execFile } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { sendManualReply } from '@/lib/outreach/replies'
import { createWinnrSmtpTransport } from '@/lib/winnr/smtp-transport'
import { authorizeEmailDispatchClaim,type DispatchRepository } from '@/lib/outreach/dispatch'
const url=process.env.OUTREACH_REPLIES_TEST_DATABASE_URL
function sql(statement:string):Promise<{code:number;out:string;err:string}>{if(!url)throw Error('Explicit reply fixture required');const u=new URL(url);if(!['postgres:','postgresql:'].includes(u.protocol)||u.hostname!=='127.0.0.1'||u.port!=='55439'||u.pathname!=='/outreach_replies_test'||u.search)throw Error('Unsafe reply fixture');const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('PG')));return new Promise(resolve=>{const child=execFile('/opt/homebrew/bin/psql',['-X','-q','-At','-v','ON_ERROR_STOP=1','--dbname',url],{env},(error,out,err)=>resolve({code:error?1:0,out:out.trim(),err}));child.stdin?.end(statement)})}
const ids={org:'11111111-1111-4111-8111-111111111111',actor:'22222222-2222-4222-8222-222222222222',conn:'33333333-3333-4333-8333-333333333333',account:'44444444-4444-4444-8444-444444444444',lead:'55555555-5555-4555-8555-555555555555',campaign:'66666666-6666-4666-8666-666666666666',endpoint:'77777777-7777-4777-8777-777777777777'}
const quote=(v:unknown)=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb"
let threadId:string,sourceReplyId:string
async function call(action:string,payload:Record<string,unknown>={},actor=ids.actor){const r=await sql(`SELECT public.outreach_reply_mutate('${actor}','${ids.org}','${action}',${quote({threadId,...payload})})`);expect(r.code,r.err).toBe(0);return JSON.parse(r.out)}
async function shared(action:string,payload:Record<string,unknown>){const r=await sql(`SELECT public.email_dispatch_mutate('${ids.actor}','${ids.org}','${action}',${quote(payload)})`);expect(r.code,r.err).toBe(0);return JSON.parse(r.out)}
const message={from:'sender@example.test',to:'lead@example.test',subject:'Re: Question',text:'Literal body',messageId:'<reply@example.test>',inReplyTo:'<incoming@example.test>',references:['<incoming@example.test>']}
async function reserve(extra:Record<string,unknown>={}){const c=await call('readiness');return call('reserve',{...c,source:'human',message,fingerprint:'a'.repeat(64),...extra})}
const auth=(token:string,extra:Record<string,unknown>={})=>shared('authorize',{claimToken:token,connectionId:ids.conn,connectionVersion:1,mailboxId:'provider-1',fingerprint:'a'.repeat(64),...extra})
describe.skipIf(!url)('029 shared durable reply ledger real PostgreSQL',()=>{
 beforeAll(async()=>{
  const r=await sql(`DROP SCHEMA IF EXISTS public CASCADE; DROP SCHEMA IF EXISTS auth CASCADE; CREATE SCHEMA public; GRANT USAGE ON SCHEMA public TO PUBLIC; CREATE SCHEMA auth; DO $$ BEGIN CREATE ROLE anon;EXCEPTION WHEN duplicate_object THEN NULL;END $$;DO $$ BEGIN CREATE ROLE authenticated;EXCEPTION WHEN duplicate_object THEN NULL;END $$;DO $$ BEGIN CREATE ROLE service_role;EXCEPTION WHEN duplicate_object THEN NULL;END $$;`+readFileSync('tests/fixtures/baseline-outreach.sql','utf8')+`ALTER TABLE auth.users ADD COLUMN email text,ADD COLUMN raw_user_meta_data jsonb;`);expect(r.code,r.err).toBe(0)
  for(const file of ['020_winnr_connections.sql','021_outreach_event_spine.sql','022_campaign_core.sql','023_outreach_suppression.sql','024_email_dispatch.sql','025_identity_bootstrap.sql','026_winnr_smtp.sql','027_winnr_ingestion.sql','028_lead_validation.sql','029_email_replies.sql']){const a=await sql(readFileSync('supabase/migrations/'+file,'utf8'));expect(a.code,a.err).toBe(0)}
 })
 beforeEach(async()=>{
  const r=await sql(`TRUNCATE public.organizations,auth.users CASCADE;
INSERT INTO public.organizations(id,name,slug) VALUES('${ids.org}','Fixture','fixture'); INSERT INTO auth.users(id,email) VALUES('${ids.actor}','owner@example.test'); INSERT INTO public.users(id,email,organization_id,role) VALUES('${ids.actor}','owner@example.test','${ids.org}','owner');
INSERT INTO public.winnr_connections(id,organization_id,provider_account_id,token_ciphertext,permissions) VALUES('${ids.conn}','${ids.org}','acct_own','synthetic','["read","write"]');
INSERT INTO public.email_accounts(id,organization_id,email,provider) VALUES('${ids.account}','${ids.org}','sender@example.test','smtp'); INSERT INTO public.winnr_mailbox_credentials(organization_id,connection_id,connection_version,provider_mailbox_id,email,account_id,credentials_ciphertext) VALUES('${ids.org}','${ids.conn}',1,'provider-1','sender@example.test','${ids.account}','synthetic');
INSERT INTO public.winnr_ingestion_endpoints(id,organization_id,connection_id,connection_version,provider_account_id,webhook_id,secret_ciphertext) VALUES('${ids.endpoint}','${ids.org}','${ids.conn}',1,'acct_own','wh_one','synthetic');
UPDATE public.winnr_ingestion_endpoints SET associated_at=now(),verified_events=ARRAY['email.received','message.relayed','email.bounced','email.complained'];
INSERT INTO public.leads(id,organization_id,email,status,validation_status) VALUES('${ids.lead}','${ids.org}','lead@example.test','active','valid');
INSERT INTO public.campaigns(id,organization_id,name,status,settings) VALUES('${ids.campaign}','${ids.org}','Fixture','paused','{"timezone":"UTC","sendingWindowStart":0,"sendingWindowEnd":24,"skipWeekends":false,"dailyLimit":10,"mailboxIds":["provider-1"],"senderConnectionId":"${ids.conn}","senderConnectionVersion":1}');
INSERT INTO public.email_dispatch_config VALUES('${ids.campaign}','${ids.org}','Approved','Company','Provided address','sender@example.test','provider-1',5,'${ids.conn}',1,false);
INSERT INTO public.campaign_leads(campaign_id,lead_id,status) VALUES('${ids.campaign}','${ids.lead}','pending');
SELECT public.winnr_receive_event('${ids.endpoint}','{"id":"evt_initial","object":"event","type":"email.received","created":"2026-10-05T00:00:00.000Z","account_id":"acct_own","data":{"mailbox":"sender@example.test","from":"lead@example.test","subject":"Question","message_id":"<incoming@example.test>"}}','${'a'.repeat(64)}');
SELECT public.winnr_save_ingested_body('${ids.actor}','${ids.org}',id,'123','Actual incoming body',false,'${ids.conn}',1) FROM public.winnr_ingested_messages;
UPDATE public.threads SET campaign_id='${ids.campaign}';`);expect(r.code,r.err).toBe(0)
  threadId=(await sql('SELECT id FROM public.threads')).out;sourceReplyId=(await sql('SELECT id FROM public.replies')).out
  const c=await call('readiness');expect(c.control.mode).toBe('assist');expect((await call('control',{mode:'human',expectedRevision:1})).allowed).toBe(true)
 })
 it('allows a manual reply after inbound stopped the cold sequence',async()=>{expect((await sql('SELECT status FROM public.campaign_leads')).out).toBe('replied');expect((await call('readiness')).ready).toBe(true);const a=await reserve();expect(a.allowed).toBe(true);expect((await auth(a.attempt.claim_token)).allowed).toBe(true)})
 it('concurrent human and unauthorized agent claims cannot duplicate the logical reply',async()=>{const results=await Promise.all([reserve(),reserve({source:'agent',decisionId:ids.actor})]);expect(results.filter(r=>r.allowed)).toHaveLength(1);expect((await sql('SELECT count(*) FROM public.email_dispatch_attempts')).out).toBe('1')})
 it('concurrent human reservations produce exactly one effect',async()=>{const results=await Promise.all([reserve(),reserve()]);expect(results.filter(r=>r.allowed)).toHaveLength(1)})
 it('takeover/control changes invalidate queued claims and preserve unknown holds',async()=>{const a=await reserve();await call('control',{mode:'human',expectedRevision:2});expect((await auth(a.attempt.claim_token)).allowed).toBe(false);const b=await reserve();expect(b.allowed).toBe(true);await auth(b.attempt.claim_token);await shared('settle',{claimToken:b.attempt.claim_token,outcome:'unknown',code:'ambiguous'});await call('control',{mode:'human',expectedRevision:3});expect((await reserve()).allowed).toBe(false)})
 it('new inbound invalidates the reserved reply even before its body is fetched',async()=>{const a=await reserve();await sql(`SELECT public.winnr_receive_event('${ids.endpoint}','{"id":"evt_new","object":"event","type":"email.received","created":"2026-10-06T00:00:00.000Z","account_id":"acct_own","data":{"mailbox":"sender@example.test","from":"lead@example.test","subject":"Question","message_id":"<new@example.test>","received_at":"2026-10-06T00:00:00.000Z"}}','${'b'.repeat(64)}')`);await sql(`UPDATE public.replies SET thread_id='${threadId}' WHERE message_id='<new@example.test>'`);expect((await auth(a.attempt.claim_token)).allowed).toBe(false)})
 it('unsubscribe and changed current lead address stop final authorization',async()=>{const a=await reserve();await sql(`SELECT public.record_outreach_suppression('${ids.org}','lead@example.test','unsubscribe','fixture')`);expect((await auth(a.attempt.claim_token)).allowed).toBe(false)})
 it('current lead address edits cannot redirect or authorize an immutable reply',async()=>{const a=await reserve();await sql(`UPDATE public.leads SET email='changed@example.test' WHERE id='${ids.lead}'`);expect((await auth(a.attempt.claim_token)).allowed).toBe(false);expect((await sql('SELECT count(*) FROM public.email_dispatch_attempts WHERE authorized_at IS NOT NULL')).out).toBe('0')})
 it('binds exact fingerprint, mailbox and recipient',async()=>{const a=await reserve();expect((await auth(a.attempt.claim_token,{fingerprint:'b'.repeat(64)})).allowed).toBe(false);expect((await auth(a.attempt.claim_token,{mailboxId:'foreign'})).allowed).toBe(false);expect((await reserve({message:{...message,to:'foreign@example.test'}})).allowed).toBe(false)})
 it('unknown lease holds never release on new request or control revision',async()=>{const a=await reserve();await auth(a.attempt.claim_token);await sql('UPDATE public.email_dispatch_attempts SET lease_expires_at=now()-interval \'1 second\'');expect((await auth(a.attempt.claim_token)).allowed).toBe(false);expect((await reserve()).allowed).toBe(false);expect((await sql('SELECT status FROM public.email_dispatch_attempts')).out).toBe('unknown')})
 it('acceptance atomically persists canonical receipt and outbound timeline exactly once',async()=>{const a=await reserve();await auth(a.attempt.claim_token);const receipt={claimToken:a.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:message.messageId};expect((await shared('settle',receipt)).status).toBe('accepted');expect((await shared('settle',receipt)).settled).toBe(false);expect((await sql('SELECT count(*) FROM public.sent_emails')).out).toBe('1');expect((await sql('SELECT count(*) FROM public.thread_messages')).out).toBe('1');expect((await sql('SELECT count(*) FROM public.replies')).out).toBe('1');expect((await sql('SELECT status FROM public.campaign_leads')).out).toBe('replied')})
 it('incoming replies to accepted manual sends remain on the controlled thread',async()=>{
 const a=await reserve();await auth(a.attempt.claim_token);await shared('settle',{claimToken:a.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:message.messageId});const r=await sql(`SELECT public.winnr_receive_event('${ids.endpoint}','{"id":"evt_next_reply","object":"event","type":"email.received","created":"2026-10-06T00:00:00.000Z","account_id":"acct_own","data":{"mailbox":"sender@example.test","from":"lead@example.test","subject":"Follow up","message_id":"<next@example.test>","in_reply_to":"<reply@example.test>"}}','${'b'.repeat(64)}')`);expect(r.code,r.err).toBe(0)
 expect((await sql(`SELECT thread_id FROM public.replies WHERE message_id='<next@example.test>'`)).out).toBe(threadId);expect((await sql('SELECT count(*) FROM public.threads')).out).toBe('1');expect((await sql('SELECT message_count FROM public.threads')).out).toBe('3');expect((await sql('SELECT count(*) FROM public.thread_messages')).out).toBe('1')
 })
 it('late threading enrichment preserves explicit human takeover when temporary threads merge',async()=>{
 const a=await reserve();await auth(a.attempt.claim_token);await shared('settle',{claimToken:a.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:message.messageId});await call('control',{mode:'assist',expectedRevision:2});
 const payload={id:'evt_unthreaded',object:'event',type:'email.received',created:'2026-10-06T00:00:00.000Z',account_id:'acct_own',data:{mailbox:'sender@example.test',from:'lead@example.test',subject:'Later',message_id:'<later@example.test>'}}
 const receive=await sql(`SELECT public.winnr_receive_event('${ids.endpoint}',${quote(payload)},'${'b'.repeat(64)}')`);expect(receive.code,receive.err).toBe(0)
 const temporary=(await sql("SELECT thread_id FROM public.replies WHERE message_id='<later@example.test>'")).out
 const takeover=await call('control',{threadId:temporary,mode:'human',expectedRevision:1});expect(takeover.allowed).toBe(true)
 const enriched=await sql(`SELECT public.winnr_receive_event('${ids.endpoint}',${quote({...payload,id:'evt_threaded',data:{...payload.data,in_reply_to:message.messageId}})},'${'c'.repeat(64)}')`);expect(enriched.code,enriched.err).toBe(0)
 expect((await sql(`SELECT mode FROM public.outreach_conversation_controls WHERE thread_id='${threadId}'`)).out).toBe('human');expect((await sql("SELECT thread_id FROM public.replies WHERE message_id='<later@example.test>'")).out).toBe(threadId);expect((await sql('SELECT count(*) FROM public.threads')).out).toBe('1')
 })
 it.each(['acct_own','acct_unrelated'])('reconnect correlation preserves controlled provenance only for %s',async(provider)=>{
 const a=await reserve();await auth(a.attempt.claim_token);await shared('settle',{claimToken:a.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:message.messageId});
 const repro=`
SELECT public.winnr_delete_connection('11111111-1111-4111-8111-111111111111','33333333-3333-4333-8333-333333333333',1);
INSERT INTO public.winnr_connections(id,organization_id,provider_account_id,token_ciphertext,permissions) VALUES('33333333-3333-4333-8333-333333333334','11111111-1111-4111-8111-111111111111','acct_own','synthetic','["read","write"]');
INSERT INTO public.winnr_mailbox_credentials(organization_id,connection_id,connection_version,provider_mailbox_id,email,account_id,credentials_ciphertext) VALUES('11111111-1111-4111-8111-111111111111','33333333-3333-4333-8333-333333333334',1,'provider-new','sender@example.test','44444444-4444-4444-8444-444444444444','synthetic');
INSERT INTO public.winnr_ingestion_endpoints(id,organization_id,connection_id,connection_version,provider_account_id,webhook_id,secret_ciphertext) VALUES('77777777-7777-4777-8777-777777777778','11111111-1111-4111-8111-111111111111','33333333-3333-4333-8333-333333333334',1,'acct_own','wh_new','synthetic');
SELECT public.winnr_receive_event('77777777-7777-4777-8777-777777777778',jsonb_build_object('id','evt_reconnect_review','object','event','type','email.received','created','2026-10-06T00:00:00.000Z','account_id','acct_own','data',jsonb_build_object('mailbox','sender@example.test','from','lead@example.test','subject','Following up','message_id','<after-reconnect@example.test>','in_reply_to',message->>'messageId')),repeat('b',64)) FROM public.email_dispatch_attempts WHERE kind='reply' AND status='accepted' LIMIT 1;
SELECT 'same_controlled_thread='||(r.thread_id=a.thread_id)::text||'; original_control='||c.mode||'; new_control='||coalesce(n.mode,'default assist') FROM public.replies r JOIN public.email_dispatch_attempts a ON a.id=r.sent_email_id JOIN public.outreach_conversation_controls c ON c.thread_id=a.thread_id LEFT JOIN public.outreach_conversation_controls n ON n.thread_id=r.thread_id WHERE r.message_id='<after-reconnect@example.test>';
SELECT 'threads='||count(*) FROM public.threads;

`.replaceAll('acct_own',provider)
 const r=await sql(repro);expect(r.code,r.err).toBe(0)
 const linked=(await sql("SELECT thread_id FROM public.replies WHERE message_id='<after-reconnect@example.test>'")).out
 expect(linked===threadId).toBe(provider==='acct_own');expect((await sql(`SELECT mode FROM public.outreach_conversation_controls WHERE thread_id='${threadId}'`)).out).toBe('human')
 })
 it.each(['reply','campaign'].flatMap(kind=>['acct_own','acct_unrelated'].flatMap(provider=>['original','mapped'].map(identity=>({kind,provider,identity})))))('exact version provenance $kind/$provider/$identity',async({kind,provider,identity})=>{
 const a=await reserve();await auth(a.attempt.claim_token);await shared('settle',{claimToken:a.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:message.messageId})
 const reference=identity==='mapped'?'<relay-version@example.test>':message.messageId
 const setup=await sql(`UPDATE public.email_dispatch_attempts SET connection_version=2,kind='${kind}' WHERE id='${a.attempt.id}'; INSERT INTO public.winnr_ingestion_endpoints(organization_id,connection_id,connection_version,provider_account_id,webhook_id,secret_ciphertext) VALUES('${ids.org}','${ids.conn}',2,'${provider}','wh_second','synthetic'); UPDATE public.winnr_connections SET version=3,provider_account_id='acct_own'; UPDATE public.winnr_mailbox_credentials SET connection_version=3; INSERT INTO public.winnr_ingestion_endpoints(id,organization_id,connection_id,connection_version,provider_account_id,webhook_id,secret_ciphertext) VALUES('77777777-7777-4777-8777-777777777779','${ids.org}','${ids.conn}',3,'acct_own','wh_third','synthetic');`+(identity==='mapped'?`INSERT INTO public.winnr_message_id_maps VALUES('${ids.org}','${ids.conn}','acct_own','${ids.account}','${message.messageId}','${reference}','lead@example.test');`:''));expect(setup.code,setup.err).toBe(0)
 const payload={id:'evt_version_proof',object:'event',type:'email.received',created:'2026-10-06T00:00:00.000Z',account_id:'acct_own',data:{mailbox:'sender@example.test',from:'lead@example.test',subject:'Version proof',message_id:'<version-proof@example.test>',in_reply_to:reference}}
 const received=await sql(`SELECT public.winnr_receive_event('77777777-7777-4777-8777-777777777779',${quote(payload)},'${'b'.repeat(64)}')`);expect(received.code,received.err).toBe(0)
 expect((await sql("SELECT coalesce(sent_email_id::text,'unlinked') FROM public.replies WHERE message_id='<version-proof@example.test>'")).out).toBe(provider==='acct_own'?a.attempt.id:'unlinked')
 if(kind==='reply'&&provider==='acct_own')expect((await sql("SELECT thread_id FROM public.replies WHERE message_id='<version-proof@example.test>'")).out).toBe(threadId)
 })
 it.each(['reserved','dispatching','unknown','accepted'])('late enrichment retains immutable %s history and disables both stale controls',async(state)=>{
 const a=await reserve();await auth(a.attempt.claim_token);await shared('settle',{claimToken:a.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:message.messageId});
 const payload={id:'evt_temporary',object:'event',type:'email.received',created:'2026-10-06T00:00:00.000Z',account_id:'acct_own',data:{mailbox:'sender@example.test',from:'lead@example.test',subject:'Later',message_id:'<temporary@example.test>'}}
 let r=await sql(`SELECT public.winnr_receive_event('${ids.endpoint}',${quote(payload)},'${'b'.repeat(64)}'); SELECT public.winnr_save_ingested_body('${ids.actor}','${ids.org}',id,'456','Fetched body',false,'${ids.conn}',1) FROM public.winnr_ingested_messages WHERE message_id='<temporary@example.test>'; UPDATE public.threads SET campaign_id='${ids.campaign}'`);expect(r.code,r.err).toBe(0)
 const temporary=(await sql("SELECT thread_id FROM public.replies WHERE message_id='<temporary@example.test>'")).out
 await call('control',{threadId:temporary,mode:'human',expectedRevision:1});const context=await call('readiness',{threadId:temporary});const queued=await call('reserve',{...context,threadId:temporary,source:'human',fingerprint:'a'.repeat(64),message:{...message,messageId:'<queued@example.test>',inReplyTo:'<temporary@example.test>'}});expect(queued.allowed).toBe(true)
 if(state!=='reserved'){expect((await auth(queued.attempt.claim_token)).allowed).toBe(true);if(state==='unknown')await shared('settle',{claimToken:queued.attempt.claim_token,outcome:'unknown',code:'ambiguous'});if(state==='accepted')await shared('settle',{claimToken:queued.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:'<queued@example.test>'})}
 r=await sql(`SELECT public.winnr_receive_event('${ids.endpoint}',${quote({...payload,id:'evt_enriched',data:{...payload.data,in_reply_to:message.messageId}})},'${'c'.repeat(64)}')`);expect(r.code,r.err).toBe(0)
 expect((await sql("SELECT thread_id FROM public.replies WHERE message_id='<temporary@example.test>'")).out).toBe(threadId)
 expect((await sql(`SELECT status||':'||thread_id::text FROM public.email_dispatch_attempts WHERE id='${queued.attempt.id}'`)).out).toBe(`${state==='reserved'?'cancelled':state}:${temporary}`)
 expect((await call('readiness',{threadId:temporary})).reason).toBe('thread_merged');expect((await auth(queued.attempt.claim_token)).allowed).toBe(false)
 expect((await sql(`SELECT mode FROM public.outreach_conversation_controls WHERE thread_id='${threadId}'`)).out).toBe('human')
 if(state==='accepted'){
  expect((await sql(`SELECT thread_id FROM public.thread_messages WHERE id='${queued.attempt.id}'`)).out).toBe(threadId)
  expect((await call('readiness')).reason).toBe('response_already_reserved')
  const revision=Number((await sql(`SELECT revision FROM public.outreach_conversation_controls WHERE thread_id='${threadId}'`)).out)
  expect((await call('reserve',{...context,threadId,controlRevision:revision,source:'human',fingerprint:'a'.repeat(64),message:{...message,messageId:'<duplicate@example.test>',inReplyTo:'<temporary@example.test>'}})).reason).toBe('response_already_reserved')
 }
 if(state==='dispatching'){
  expect((await shared('settle',{claimToken:queued.attempt.claim_token,outcome:'accepted',recipient:message.to,messageId:'<queued@example.test>'})).status).toBe('accepted')
  expect((await sql(`SELECT thread_id FROM public.thread_messages WHERE id='${queued.attempt.id}'`)).out).toBe(threadId)
  const followup=await sql(`SELECT public.winnr_receive_event('${ids.endpoint}',${quote({...payload,id:'evt_audit_followup',data:{...payload.data,message_id:'<audit-followup@example.test>',in_reply_to:'<queued@example.test>'}})},'${'d'.repeat(64)}')`);expect(followup.code,followup.err).toBe(0)
  expect((await sql("SELECT thread_id FROM public.replies WHERE message_id='<audit-followup@example.test>'")).out).toBe(threadId)
 }

 })
 it('mismatched SMTP receipt holds without persisting a fake sent message',async()=>{const a=await reserve();await auth(a.attempt.claim_token);expect((await shared('settle',{claimToken:a.attempt.claim_token,outcome:'accepted',recipient:'foreign@example.test',messageId:message.messageId})).status).toBe('unknown');expect((await sql('SELECT count(*) FROM public.sent_emails')).out).toBe('0')})
 it('shared mailbox caps include earlier campaign effects across connection rotation',async()=>{await sql('UPDATE public.email_dispatch_config SET mailbox_daily_limit=1');const a=await reserve();await sql(`INSERT INTO public.email_dispatch_attempts SELECT gen_random_uuid(),organization_id,actor_id,campaign_id,enrollment_id,lead_id,99,revision,sequence_snapshot,settings_snapshot,'99999999-9999-4999-8999-999999999999',connection_version,mailbox_id,account_id,message||'{"to":"other@example.test"}',fingerprint,gen_random_uuid(),'unknown',lease_expires_at,created_at,now(),now(),NULL,NULL,'campaign',NULL,NULL,NULL,NULL,NULL FROM public.email_dispatch_attempts; UPDATE public.email_dispatch_config SET mailbox_daily_limit=1`);expect((await auth(a.attempt.claim_token)).reason).toBe('daily_cap')})
 it('canonical mailbox address edits revoke a reserved claim',async()=>{const a=await reserve();await sql(`UPDATE public.email_accounts SET email='different@example.test' WHERE id='${ids.account}'`);expect((await auth(a.attempt.claim_token)).allowed).toBe(false)})
 it('tenant and member boundaries reject SQL mutation authority',async()=>{
 const member='22222222-2222-4222-8222-222222222223';await sql(`INSERT INTO auth.users(id,email) VALUES('${member}','member@example.test'); INSERT INTO public.users(id,email,organization_id,role) VALUES('${member}','member@example.test','${ids.org}','member')`)
 expect((await sql(`SELECT public.outreach_reply_mutate('${member}','${ids.org}','readiness',${quote({threadId})})`)).code).toBe(1)
 expect((await sql(`SELECT public.outreach_reply_mutate('${ids.actor}','11111111-1111-4111-8111-111111111112','readiness',${quote({threadId})})`)).code).toBe(1)
 })
 it('browser cannot invoke old private campaign RPC or reply mutations',async()=>{for(const role of ['anon','authenticated','service_role']){expect((await sql(`SET ROLE ${role};SELECT public.email_dispatch_mutate_024('${ids.actor}','${ids.org}','readiness','{}')`)).code).toBe(1)}expect((await sql(`SET ROLE authenticated;SELECT public.outreach_reply_mutate('${ids.actor}','${ids.org}','readiness','{}')`)).code).toBe(1)})
 it('missing ingestion association gates campaign and reply final authorization',async()=>{const a=await reserve();await sql('UPDATE public.winnr_ingestion_endpoints SET webhook_id=NULL,secret_ciphertext=NULL');expect((await auth(a.attempt.claim_token)).allowed).not.toBe(true);expect((await shared('readiness',{campaignId:ids.campaign})).reason).toBe('ingestion_not_configured')})
 it('preserves working campaign start/reserve/authorize/settle through the029 shared wrapper',async()=>{
 const prospect='55555555-5555-4555-8555-555555555556',enrollment='88888888-8888-4888-8888-888888888888';const setup=await sql(`INSERT INTO public.leads(id,organization_id,email,validation_status) VALUES('${prospect}','${ids.org}','prospect@example.test','valid'); INSERT INTO public.lead_validation_evidence(organization_id,lead_id,email,validation_status,verification_level,source,checked_at) VALUES('${ids.org}','${prospect}','prospect@example.test','valid','verified_provider','synthetic_fixture',now()); INSERT INTO public.campaign_leads(id,campaign_id,lead_id,status,current_step) VALUES('${enrollment}','${ids.campaign}','${prospect}','pending',0); INSERT INTO public.campaign_sequences(campaign_id,step_number,subject,body_html,body_text,delay_days,delay_hours,condition_type) VALUES('${ids.campaign}',1,'Approved','','Approved',0,0,'always')`);expect(setup.code,setup.err).toBe(0)
 expect((await shared('start',{campaignId:ids.campaign})).ready).toBe(true);const c=(await shared('candidates',{campaignId:ids.campaign,limit:1})).candidates[0];expect(c.enrollmentId).toBe(enrollment)
 const outbound={...message,to:'prospect@example.test',messageId:'<campaign@example.test>'};const a=await shared('reserve',{campaignId:ids.campaign,enrollmentId:enrollment,step:c.step,configuration:c.configuration,message:outbound,fingerprint:'a'.repeat(64)});expect(a.allowed).toBe(true);expect(a.attempt.kind).toBe('campaign');expect((await auth(a.attempt.claim_token)).allowed).toBe(true);expect((await shared('settle',{claimToken:a.attempt.claim_token,outcome:'accepted',recipient:outbound.to,messageId:outbound.messageId})).status).toBe('accepted');expect((await sql(`SELECT current_step FROM public.campaign_leads WHERE id='${enrollment}'`)).out).toBe('1')
 })
 it('real SQL and fake SMTP complete one manual reply without provider calls',async()=>{
  process.env.ENCRYPTION_SECRET='synthetic-fixture-only'
  const repo:DispatchRepository={call:async(actor,org,action,payload)=>{const r=await sql(`SELECT public.outreach_reply_mutate('${actor}','${org}','${action}',${quote(payload)})`);if(r.code)throw Error(r.err);return JSON.parse(r.out)}}
  const authRepo:DispatchRepository={call:async(actor,org,action,payload)=>{const r=await sql(`SELECT public.email_dispatch_mutate('${actor}','${org}','${action}',${quote(Object.fromEntries(Object.entries(payload).filter(([,v])=>v!==undefined)))})`);if(r.code)throw Error(r.err);return JSON.parse(r.out)}}
  let effects=0
  const transport=createWinnrSmtpTransport({sendTimeoutMs:1000,loadCredentials:async()=>({providerMailboxId:'provider-1',domain:'example.test',fromEmail:'sender@example.test',fromName:'Fixture',smtpHost:'smtp.example.test',smtpPort:465,smtpUsername:'sender@example.test',smtpPassword:'synthetic',imapHost:'imap.example.test',imapPort:993,imapUsername:'sender@example.test',imapPassword:'synthetic',footer:''}),resolve:async()=>[{address:'1.1.1.1',family:4}],authorizeClaim:input=>authorizeEmailDispatchClaim(authRepo,ids.actor,input),createTransport:()=>({sendMail:async m=>{effects++;return{accepted:['lead@example.test'],rejected:[],messageId:String(m.messageId)}},close:()=>{}})})
  const result=await sendManualReply(ids.actor,ids.org,threadId,{message:'Human reply',sourceReplyId,controlRevision:2},{repository:repo,transport,mailboxAvailable:async()=>true,appUrl:'https://fixture.example'})
  expect(result.accepted).toBe(true);expect(effects).toBe(1);expect((await sql('SELECT body_text FROM public.sent_emails')).out).toContain('Unsubscribe:')
 })
})
