BEGIN;
CREATE TABLE public.outreach_agent_models(organization_id uuid PRIMARY KEY REFERENCES public.organizations(id),revision bigint NOT NULL DEFAULT 1,model text NOT NULL,api_key_ciphertext text,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.outreach_offer_briefs(organization_id uuid NOT NULL REFERENCES public.organizations(id),campaign_id uuid PRIMARY KEY REFERENCES public.campaigns(id),revision bigint NOT NULL DEFAULT 1,brief jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.outreach_agent_policies(organization_id uuid NOT NULL REFERENCES public.organizations(id),campaign_id uuid PRIMARY KEY REFERENCES public.campaigns(id),revision bigint NOT NULL DEFAULT 1,policy jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.outreach_agent_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id),campaign_id uuid NOT NULL REFERENCES public.campaigns(id),kind text NOT NULL CHECK(kind IN('copy','classify')),context_key text NOT NULL,source_reply_id uuid REFERENCES public.replies(id),source_body_hash text,brief_revision bigint NOT NULL,policy_revision bigint NOT NULL,model text NOT NULL,served_model text,prompt_version text NOT NULL DEFAULT 'outreach-v1',status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','succeeded','rejected','unknown')),result jsonb,error_code text,created_at timestamptz NOT NULL DEFAULT now(),settled_at timestamptz,UNIQUE(organization_id,kind,context_key));
CREATE TABLE public.outreach_agent_drafts(id uuid PRIMARY KEY REFERENCES public.outreach_agent_runs(id),organization_id uuid NOT NULL REFERENCES public.organizations(id),campaign_id uuid NOT NULL REFERENCES public.campaigns(id),brief_revision bigint NOT NULL,content jsonb NOT NULL,approved_at timestamptz,approved_by uuid,approved_campaign_revision timestamptz);
CREATE TABLE public.outreach_agent_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES public.organizations(id),campaign_id uuid NOT NULL REFERENCES public.campaigns(id),thread_id uuid NOT NULL REFERENCES public.threads(id),source_reply_id uuid NOT NULL REFERENCES public.replies(id),control_revision bigint NOT NULL,brief_revision bigint NOT NULL,policy_revision bigint NOT NULL,source_body_hash text NOT NULL,classification jsonb NOT NULL,prepared jsonb,template_id text,fingerprint text,approved boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,source_reply_id,policy_revision,control_revision));
DO $$ DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['outreach_agent_models','outreach_offer_briefs','outreach_agent_policies','outreach_agent_runs','outreach_agent_drafts','outreach_agent_decisions'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC,anon,authenticated,service_role',t);EXECUTE format('GRANT SELECT ON public.%I TO service_role',t);END LOOP;END $$;
CREATE FUNCTION public.outreach_reply_decision_is_authorized(p_org uuid,p_thread uuid,p_source_reply uuid,p_control_revision bigint,p_decision uuid,p_fingerprint text,p_now timestamptz) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
 SELECT EXISTS(SELECT 1 FROM public.outreach_agent_decisions d JOIN public.outreach_agent_policies p ON p.campaign_id=d.campaign_id AND p.organization_id=d.organization_id JOIN public.outreach_offer_briefs b ON b.campaign_id=d.campaign_id AND b.organization_id=d.organization_id JOIN public.outreach_conversation_controls c ON c.thread_id=d.thread_id AND c.organization_id=d.organization_id JOIN public.replies r ON r.id=d.source_reply_id AND r.organization_id=d.organization_id AND r.thread_id=d.thread_id WHERE d.id=p_decision AND d.organization_id=p_org AND d.thread_id=p_thread AND d.source_reply_id=p_source_reply AND d.control_revision=p_control_revision AND c.revision=p_control_revision AND c.mode='autonomous' AND d.approved AND EXISTS(SELECT 1 FROM public.winnr_ingested_messages im WHERE im.organization_id=p_org AND im.reply_id=r.id AND im.body_status='ready') AND d.source_body_hash=pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(r.body_text,''),'UTF8')),'hex') AND r.body_text !~* '(unsubscribe|opt.?out|remove me|stop (emailing|contacting|sending)|automatic reply|auto.?reply|out of (the )?office|on vacation|ignore .{0,40}instructions|disregard .{0,40}(instructions|rules)|system( prompt|:)|send (the |your )?(password|secret))' AND d.fingerprint=p_fingerprint AND d.policy_revision=p.revision AND d.brief_revision=b.revision AND (p.policy->>'enabled')::boolean AND (d.classification->>'confidence')::numeric >= (p.policy->>'minConfidence')::numeric AND p.policy->'allowedIntents' ? (d.classification->>'intent') AND EXISTS(SELECT 1 FROM jsonb_array_elements(b.brief->'faqs') f WHERE f->>'id'=d.template_id AND f->>'intent'=d.classification->>'intent' AND f->>'answer' !~ '([{][{]|[$][{])' AND f->>'answer' !~* '(appointment.{0,30}(confirmed|booked)|i( have|''ve)? booked|we will call|call you|you (consent|agreed))' AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(b.brief->'exclusions') x WHERE position(lower(x) IN lower(f->>'answer'))>0) AND left(d.prepared->'message'->>'text',length(f->>'answer')+2)=(f->>'answer')||E'\n\n') AND r.id=(SELECT id FROM public.replies WHERE organization_id=p_org AND thread_id=p_thread ORDER BY received_at DESC NULLS LAST,created_at DESC NULLS LAST,id DESC LIMIT 1) AND extract(hour FROM p_now AT TIME ZONE 'UTC') >= (p.policy->>'startHour')::int AND extract(hour FROM p_now AT TIME ZONE 'UTC') < (p.policy->>'endHour')::int AND p_now>=d.created_at AND p_now<d.created_at+interval '15 minutes' AND (SELECT count(*) FROM public.email_dispatch_attempts a WHERE a.organization_id=p_org AND public.outreach_canonical_reply_thread(p_org,a.thread_id)=public.outreach_canonical_reply_thread(p_org,p_thread) AND a.kind='reply' AND a.reply_source<>'human' AND a.status IN('reserved','dispatching','accepted','unknown') AND a.policy_decision_id IS DISTINCT FROM d.id)<(p.policy->>'maxReplies')::int);
$$;
CREATE FUNCTION public.outreach_agent_mutate(p_actor uuid,p_org uuid,p_action text,p_payload jsonb DEFAULT '{}') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE cid uuid;rev bigint; b public.outreach_offer_briefs;p public.outreach_agent_policies;m public.outreach_agent_models;run public.outreach_agent_runs;d public.outreach_agent_drafts;ctl public.outreach_conversation_controls;r public.replies;decision public.outreach_agent_decisions;now_at timestamptz:=clock_timestamp();answer text;approved boolean:=false;classification jsonb;canonical jsonb;spine jsonb;steps jsonb;target uuid;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtextextended('email-dispatch:'||p_org::text,0));
 PERFORM 1 FROM public.users WHERE id=p_actor AND organization_id=p_org AND role IN('owner','admin') FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'agents:forbidden';END IF;
 IF p_action='read' THEN RETURN jsonb_build_object('model',(SELECT jsonb_build_object('revision',revision,'model',model,'configured',api_key_ciphertext IS NOT NULL) FROM public.outreach_agent_models WHERE organization_id=p_org),'briefs',coalesce((SELECT jsonb_agg(to_jsonb(x)) FROM public.outreach_offer_briefs x WHERE organization_id=p_org),'[]'),'policies',coalesce((SELECT jsonb_agg(to_jsonb(x)) FROM public.outreach_agent_policies x WHERE organization_id=p_org),'[]'),'drafts',coalesce((SELECT jsonb_agg(to_jsonb(x)) FROM public.outreach_agent_drafts x WHERE organization_id=p_org),'[]'),'runs',coalesce((SELECT jsonb_agg(to_jsonb(x)-'result') FROM (SELECT * FROM public.outreach_agent_runs WHERE organization_id=p_org ORDER BY created_at DESC LIMIT 30)x),'[]'),'decisions',coalesce((SELECT jsonb_agg(to_jsonb(x)-'prepared') FROM (SELECT * FROM public.outreach_agent_decisions WHERE organization_id=p_org ORDER BY created_at DESC LIMIT 30)x),'[]'));END IF;
 IF p_action='model' THEN
  SELECT * INTO m FROM public.outreach_agent_models WHERE organization_id=p_org FOR UPDATE;IF coalesce(m.revision,0) IS DISTINCT FROM (p_payload->>'expectedRevision')::bigint THEN RAISE EXCEPTION 'agents:stale';END IF;
  IF length(p_payload->>'model') NOT BETWEEN 1 AND 120 THEN RAISE EXCEPTION 'agents:invalid';END IF;
  INSERT INTO public.outreach_agent_models(organization_id,model,api_key_ciphertext) VALUES(p_org,p_payload->>'model',p_payload->>'ciphertext') ON CONFLICT(organization_id) DO UPDATE SET revision=outreach_agent_models.revision+1,model=EXCLUDED.model,api_key_ciphertext=coalesce(EXCLUDED.api_key_ciphertext,outreach_agent_models.api_key_ciphertext),updated_at=now_at;
  RETURN jsonb_build_object('saved',true);
 END IF;
 IF p_action='nextDecision' THEN
  SELECT t.id INTO cid FROM public.threads t JOIN public.outreach_agent_policies ap ON ap.campaign_id=t.campaign_id AND ap.organization_id=t.organization_id JOIN LATERAL(SELECT rr.* FROM public.replies rr WHERE rr.organization_id=t.organization_id AND rr.thread_id=t.id ORDER BY received_at DESC NULLS LAST,created_at DESC NULLS LAST,id DESC LIMIT 1) latest ON true JOIN public.winnr_ingested_messages im ON im.reply_id=latest.id AND im.organization_id=p_org AND im.body_status='ready' LEFT JOIN public.outreach_conversation_controls cc ON cc.organization_id=p_org AND cc.thread_id=t.id WHERE t.organization_id=p_org AND coalesce(cc.mode,'assist')<>'human' AND (ap.policy->>'enabled')::boolean AND extract(hour FROM now_at AT TIME ZONE 'UTC') >= (ap.policy->>'startHour')::int AND extract(hour FROM now_at AT TIME ZONE 'UTC') < (ap.policy->>'endHour')::int AND NOT EXISTS(SELECT 1 FROM public.outreach_agent_decisions ad WHERE ad.organization_id=p_org AND ad.source_reply_id=latest.id) AND NOT EXISTS(SELECT 1 FROM public.outreach_agent_runs ar WHERE ar.organization_id=p_org AND ar.kind='classify' AND ar.status<>'succeeded' AND ar.context_key LIKE 'reply:'||latest.id::text||':%') ORDER BY latest.received_at ASC NULLS LAST,t.id LIMIT 1;
  RETURN jsonb_build_object('threadId',cid);
 END IF;
 IF p_action='nextApproved' THEN
  SELECT * INTO decision FROM public.outreach_agent_decisions ad WHERE ad.organization_id=p_org AND ad.approved AND NOT EXISTS(SELECT 1 FROM public.email_dispatch_attempts a WHERE a.organization_id=p_org AND a.thread_id=ad.thread_id AND a.source_reply_id=ad.source_reply_id AND a.kind='reply' AND a.status<>'cancelled') AND public.outreach_reply_decision_is_authorized(p_org,ad.thread_id,ad.source_reply_id,ad.control_revision,ad.id,ad.fingerprint,now_at) ORDER BY ad.created_at,ad.id LIMIT 1;
  RETURN CASE WHEN decision.id IS NULL THEN jsonb_build_object('decisionId',NULL) ELSE jsonb_build_object('decisionId',decision.id,'prepared',decision.prepared) END;
 END IF;
 IF p_action='conversation' THEN
  PERFORM 1 FROM public.threads WHERE id=(p_payload->>'threadId')::uuid AND organization_id=p_org;IF NOT FOUND THEN RAISE EXCEPTION 'agents:not_found';END IF;
  INSERT INTO public.outreach_conversation_controls(organization_id,thread_id,updated_by) VALUES(p_org,(p_payload->>'threadId')::uuid,p_actor) ON CONFLICT DO NOTHING;
  SELECT * INTO ctl FROM public.outreach_conversation_controls WHERE organization_id=p_org AND thread_id=(p_payload->>'threadId')::uuid;
  SELECT * INTO r FROM public.replies WHERE organization_id=p_org AND thread_id=ctl.thread_id ORDER BY received_at DESC NULLS LAST,created_at DESC NULLS LAST,id DESC LIMIT 1;
  IF r.body_text IS NULL OR NOT EXISTS(SELECT 1 FROM public.winnr_ingested_messages WHERE organization_id=p_org AND reply_id=r.id AND body_status='ready') THEN RAISE EXCEPTION 'agents:body_required';END IF;
  SELECT campaign_id INTO cid FROM public.threads WHERE id=ctl.thread_id AND organization_id=p_org;
  SELECT * INTO b FROM public.outreach_offer_briefs WHERE campaign_id=cid AND organization_id=p_org;SELECT * INTO p FROM public.outreach_agent_policies WHERE campaign_id=cid AND organization_id=p_org;
  RETURN jsonb_build_object('campaignId',cid,'sourceReplyId',r.id,'controlRevision',ctl.revision,'mode',ctl.mode,'bodyHash',pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(r.body_text,''),'UTF8')),'hex'),'body',left(r.body_text,16001),'brief',b.brief,'briefRevision',b.revision,'policy',p.policy,'policyRevision',p.revision);
 END IF;
 cid:=(p_payload->>'campaignId')::uuid;
 IF p_action IN('finish','approveDraft','applyDraft') THEN SELECT * INTO run FROM public.outreach_agent_runs WHERE id=(p_payload->>'runId')::uuid AND organization_id=p_org FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'agents:not_found';END IF;cid:=run.campaign_id;END IF;
 PERFORM 1 FROM public.campaigns WHERE id=cid AND organization_id=p_org;IF NOT FOUND THEN RAISE EXCEPTION 'agents:not_found';END IF;
 SELECT * INTO b FROM public.outreach_offer_briefs WHERE campaign_id=cid AND organization_id=p_org FOR UPDATE;SELECT * INTO p FROM public.outreach_agent_policies WHERE campaign_id=cid AND organization_id=p_org FOR UPDATE;
 IF p_action='brief' THEN
  IF coalesce(b.revision,0) IS DISTINCT FROM (p_payload->>'expectedRevision')::bigint THEN RAISE EXCEPTION 'agents:stale';END IF;
  IF jsonb_typeof(p_payload->'brief')<>'object' THEN RAISE EXCEPTION 'agents:invalid';END IF;
  INSERT INTO public.outreach_offer_briefs(organization_id,campaign_id,brief) VALUES(p_org,cid,p_payload->'brief') ON CONFLICT(campaign_id) DO UPDATE SET brief=EXCLUDED.brief,revision=outreach_offer_briefs.revision+1,updated_at=now_at;RETURN jsonb_build_object('saved',true);
 ELSIF p_action='policy' THEN
  IF coalesce(p.revision,0) IS DISTINCT FROM (p_payload->>'expectedRevision')::bigint THEN RAISE EXCEPTION 'agents:stale';END IF;
  IF jsonb_typeof(p_payload->'policy')<>'object' OR (p_payload->'policy'->>'dailyCalls')::int NOT BETWEEN 1 AND 200 OR (p_payload->'policy'->>'maxReplies')::int NOT BETWEEN 1 AND 3 OR (p_payload->'policy'->>'minConfidence')::numeric NOT BETWEEN 0.9 AND 1 THEN RAISE EXCEPTION 'agents:invalid';END IF;
  INSERT INTO public.outreach_agent_policies(organization_id,campaign_id,policy) VALUES(p_org,cid,p_payload->'policy') ON CONFLICT(campaign_id) DO UPDATE SET policy=EXCLUDED.policy,revision=outreach_agent_policies.revision+1,updated_at=now_at;RETURN jsonb_build_object('saved',true);
 ELSIF p_action='manualDraft' THEN
  IF b.campaign_id IS NULL OR b.revision IS DISTINCT FROM (p_payload->>'expectedBriefRevision')::bigint OR jsonb_typeof(p_payload->'content')<>'object' THEN RAISE EXCEPTION 'agents:stale';END IF;
  INSERT INTO public.outreach_agent_runs(organization_id,campaign_id,kind,context_key,brief_revision,policy_revision,model,prompt_version,status,result,settled_at) VALUES(p_org,cid,'copy','manual:'||gen_random_uuid()::text,b.revision,coalesce(p.revision,0),'manual','manual-approval-v1','succeeded',p_payload->'content',now_at) RETURNING * INTO run;
  INSERT INTO public.outreach_agent_drafts(id,organization_id,campaign_id,brief_revision,content) VALUES(run.id,p_org,cid,b.revision,p_payload->'content');RETURN jsonb_build_object('runId',run.id);
 ELSIF p_action='reserve' THEN
  IF p_payload ? 'expectedBriefRevision' AND (b.revision IS DISTINCT FROM (p_payload->>'expectedBriefRevision')::bigint OR p.revision IS DISTINCT FROM (p_payload->>'expectedPolicyRevision')::bigint) THEN RAISE EXCEPTION 'agents:stale';END IF;
  SELECT * INTO m FROM public.outreach_agent_models WHERE organization_id=p_org;IF m.api_key_ciphertext IS NULL OR b.campaign_id IS NULL OR p.campaign_id IS NULL THEN RETURN jsonb_build_object('allowed',false,'reason','setup_required');END IF;
  IF length(p_payload->>'context') NOT BETWEEN 1 AND 200 OR p_payload->>'kind' NOT IN('copy','classify') THEN RAISE EXCEPTION 'agents:invalid';END IF;
  SELECT * INTO run FROM public.outreach_agent_runs WHERE organization_id=p_org AND kind=p_payload->>'kind' AND context_key=p_payload->>'context';IF FOUND AND run.kind='classify' AND run.source_body_hash IS DISTINCT FROM p_payload->>'sourceBodyHash' THEN RETURN jsonb_build_object('allowed',false,'reason','context_body_changed','runId',run.id,'status',run.status);END IF;
 IF FOUND THEN RETURN jsonb_build_object('allowed',false,'reason','context_already_reserved','status',run.status,'runId',run.id,'sourceBodyHash',run.source_body_hash,'result',CASE WHEN run.status='succeeded' AND run.kind='classify' THEN run.result ELSE NULL END);END IF;
  IF p_payload->>'kind'='classify' THEN
   SELECT * INTO r FROM public.replies WHERE organization_id=p_org AND id=(p_payload->>'sourceReplyId')::uuid;
   IF NOT FOUND OR r.thread_id IS DISTINCT FROM (p_payload->>'threadId')::uuid OR NOT EXISTS(SELECT 1 FROM public.threads WHERE id=r.thread_id AND organization_id=p_org AND campaign_id=cid) OR pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(r.body_text,''),'UTF8')),'hex') IS DISTINCT FROM p_payload->>'sourceBodyHash' OR r.id IS DISTINCT FROM (SELECT id FROM public.replies WHERE organization_id=p_org AND thread_id=r.thread_id ORDER BY received_at DESC NULLS LAST,created_at DESC NULLS LAST,id DESC LIMIT 1) THEN RAISE EXCEPTION 'agents:stale_body';END IF;
  END IF;
  IF (SELECT count(*) FROM public.outreach_agent_runs WHERE organization_id=p_org AND model<>'manual' AND created_at>=date_trunc('day',now_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC') >= (p.policy->>'dailyCalls')::int THEN RETURN jsonb_build_object('allowed',false,'reason','daily_budget');END IF;
  INSERT INTO public.outreach_agent_runs(organization_id,campaign_id,kind,context_key,source_reply_id,source_body_hash,brief_revision,policy_revision,model) VALUES(p_org,cid,p_payload->>'kind',p_payload->>'context',(p_payload->>'sourceReplyId')::uuid,p_payload->>'sourceBodyHash',b.revision,p.revision,m.model) RETURNING * INTO run;RETURN jsonb_build_object('allowed',true,'runId',run.id,'model',m.model,'brief',b.brief,'briefRevision',b.revision,'policy',p.policy,'policyRevision',p.revision);
 ELSIF p_action='finish' THEN
  IF run.status<>'pending' THEN RETURN jsonb_build_object('saved',false);END IF;
  IF p_payload->>'status' NOT IN('succeeded','rejected','unknown') THEN RAISE EXCEPTION 'agents:invalid';END IF;
  IF run.kind='classify' AND p_payload->>'status'='succeeded' AND NOT EXISTS(SELECT 1 FROM public.replies WHERE id=run.source_reply_id AND organization_id=p_org AND pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(body_text,''),'UTF8')),'hex')=run.source_body_hash) THEN UPDATE public.outreach_agent_runs SET status='rejected',error_code='source_body_changed',settled_at=now_at WHERE id=run.id;RETURN jsonb_build_object('saved',false,'reason','source_body_changed');END IF;
  UPDATE public.outreach_agent_runs SET status=p_payload->>'status',served_model=left(p_payload->>'servedModel',120),result=p_payload->'result',error_code=left(p_payload->>'errorCode',80),settled_at=now_at WHERE id=run.id;
  IF run.kind='copy' AND p_payload->>'status'='succeeded' THEN INSERT INTO public.outreach_agent_drafts(id,organization_id,campaign_id,brief_revision,content) VALUES(run.id,p_org,cid,run.brief_revision,p_payload->'result');END IF;
  RETURN jsonb_build_object('saved',true);
 ELSIF p_action='approveDraft' THEN
  SELECT * INTO d FROM public.outreach_agent_drafts WHERE id=run.id AND organization_id=p_org FOR UPDATE;IF NOT FOUND OR d.brief_revision<>b.revision THEN RAISE EXCEPTION 'agents:stale';END IF;
  UPDATE public.outreach_agent_drafts SET approved_at=now_at,approved_by=p_actor,approved_campaign_revision=(SELECT updated_at FROM public.campaigns WHERE id=cid AND organization_id=p_org) WHERE id=d.id;RETURN jsonb_build_object('approved',true);
 ELSIF p_action='applyDraft' THEN
  SELECT * INTO d FROM public.outreach_agent_drafts WHERE id=run.id AND organization_id=p_org FOR UPDATE;
  IF NOT FOUND OR d.approved_at IS NULL OR d.brief_revision<>b.revision OR d.approved_campaign_revision IS DISTINCT FROM (p_payload->>'expectedUpdatedAt')::timestamptz THEN RAISE EXCEPTION 'agents:stale';END IF;
  target:=(p_payload->>'stepId')::uuid;
  PERFORM 1 FROM public.campaign_sequences WHERE id=target AND campaign_id=cid;IF NOT FOUND THEN RAISE EXCEPTION 'agents:not_found';END IF;
  SELECT jsonb_agg(jsonb_build_object('step_number',step_number,'subject',CASE WHEN id=target THEN d.content->>'subject' ELSE subject END,'body_html',CASE WHEN id=target THEN '' ELSE body_html END,'body_text',CASE WHEN id=target THEN d.content->>'body' ELSE body_text END,'delay_days',delay_days,'delay_hours',delay_hours,'condition_type',condition_type) ORDER BY step_number) INTO steps FROM public.campaign_sequences WHERE campaign_id=cid;
  RETURN public.campaign_core_mutate(p_actor,p_org,cid,'sequence',jsonb_build_object('steps',steps),(p_payload->>'expectedUpdatedAt')::timestamptz);
 ELSIF p_action='enableThread' THEN
  IF NOT coalesce((p.policy->>'enabled')::boolean,false) THEN RAISE EXCEPTION 'agents:disabled';END IF;
  PERFORM 1 FROM public.threads WHERE id=(p_payload->>'threadId')::uuid AND organization_id=p_org AND campaign_id=cid;IF NOT FOUND THEN RAISE EXCEPTION 'agents:not_found';END IF;
  INSERT INTO public.outreach_conversation_controls(organization_id,thread_id,updated_by) VALUES(p_org,(p_payload->>'threadId')::uuid,p_actor) ON CONFLICT DO NOTHING;
  UPDATE public.outreach_conversation_controls SET mode='autonomous',revision=revision+1,updated_at=now_at,updated_by=p_actor WHERE organization_id=p_org AND thread_id=(p_payload->>'threadId')::uuid AND mode='assist';RETURN jsonb_build_object('saved',true);
 ELSIF p_action='decision' THEN
  IF NOT EXISTS(SELECT 1 FROM public.threads WHERE id=(p_payload->>'threadId')::uuid AND organization_id=p_org AND campaign_id=cid) OR b.revision IS DISTINCT FROM (p_payload->>'expectedBriefRevision')::bigint OR p.revision IS DISTINCT FROM (p_payload->>'expectedPolicyRevision')::bigint THEN RAISE EXCEPTION 'agents:stale';END IF;
  SELECT * INTO ctl FROM public.outreach_conversation_controls WHERE organization_id=p_org AND thread_id=(p_payload->>'threadId')::uuid FOR UPDATE;
  SELECT * INTO r FROM public.replies WHERE organization_id=p_org AND thread_id=ctl.thread_id ORDER BY received_at DESC NULLS LAST,created_at DESC NULLS LAST,id DESC LIMIT 1 FOR UPDATE;
  IF r.id IS DISTINCT FROM (p_payload->>'sourceReplyId')::uuid OR ctl.revision IS DISTINCT FROM (p_payload->>'controlRevision')::bigint THEN RAISE EXCEPTION 'agents:stale';END IF;
  IF p_payload->>'sourceBodyHash' IS DISTINCT FROM pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(r.body_text,''),'UTF8')),'hex') THEN RAISE EXCEPTION 'agents:stale_body';END IF;
  classification:=p_payload->'classification';
  IF classification->>'source'='model' AND NOT EXISTS(SELECT 1 FROM public.outreach_agent_runs WHERE id=(p_payload->>'runId')::uuid AND organization_id=p_org AND campaign_id=cid AND source_reply_id=r.id AND source_body_hash=p_payload->>'sourceBodyHash' AND status='succeeded' AND result=classification) THEN RAISE EXCEPTION 'agents:stale_body';END IF;

  SELECT f->>'answer' INTO answer FROM jsonb_array_elements(b.brief->'faqs') f WHERE f->>'id'=classification->>'templateId' AND f->>'intent'=classification->>'intent';
  approved:=ctl.mode='autonomous' AND coalesce((p.policy->>'enabled')::boolean,false) AND classification->>'source'='model' AND r.body_text !~* '(unsubscribe|opt.?out|remove me|stop (emailing|contacting|sending)|automatic reply|auto.?reply|out of (the )?office|on vacation|ignore .{0,40}instructions|disregard .{0,40}(instructions|rules)|system( prompt|:)|send (the |your )?(password|secret))' AND (classification->>'confidence')::numeric >= (p.policy->>'minConfidence')::numeric AND p.policy->'allowedIntents' ? (classification->>'intent') AND answer IS NOT NULL AND left(p_payload->'prepared'->'message'->>'text',length(answer)+2)=answer||E'\n\n' AND p_payload->'prepared'->'context'->>'sourceReplyId'=r.id::text AND p_payload->'prepared'->'context'->>'threadId'=ctl.thread_id::text AND p_payload->'prepared'->'context'->>'recipient'=lower(btrim(r.from_email)) AND p_payload->'prepared'->>'fingerprint'=p_payload->>'fingerprint' AND p_payload->>'fingerprint' ~ '^[0-9a-f]{64}$';
  IF classification->>'intent'='optout' THEN PERFORM public.record_outreach_suppression(p_org,r.from_email,'unsubscribe','conversation_agent',NULL,NULL,NULL,r.lead_id);UPDATE public.outreach_conversation_controls SET mode='human',revision=revision+1 WHERE organization_id=p_org AND thread_id=ctl.thread_id;approved:=false;END IF;
  INSERT INTO public.outreach_agent_decisions(organization_id,campaign_id,thread_id,source_reply_id,control_revision,brief_revision,policy_revision,source_body_hash,classification,prepared,template_id,fingerprint,approved) VALUES(p_org,cid,ctl.thread_id,r.id,ctl.revision,b.revision,p.revision,p_payload->>'sourceBodyHash',classification,p_payload->'prepared',classification->>'templateId',p_payload->>'fingerprint',coalesce(approved,false)) ON CONFLICT(organization_id,source_reply_id,policy_revision,control_revision) DO NOTHING RETURNING * INTO decision;
  IF decision.id IS NULL THEN RETURN jsonb_build_object('approved',false,'reason','decision_exists');END IF;
  IF decision.approved AND NOT public.outreach_reply_decision_is_authorized(p_org,ctl.thread_id,r.id,ctl.revision,decision.id,decision.fingerprint,now_at) THEN UPDATE public.outreach_agent_decisions SET approved=false WHERE id=decision.id RETURNING * INTO decision;END IF;
  canonical:=jsonb_build_object('version',1,'organizationId',p_org,'type','conversation.decision.recorded','source','outreach.agents','sourceEventId',decision.id::text,'occurredAt',to_char(now_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'correlationId',ctl.thread_id::text,'causationId',r.id::text,'subject',jsonb_strip_nulls(jsonb_build_object('leadId',r.lead_id,'campaignId',cid,'messageId',r.id)),'data',jsonb_build_object('decisionId',decision.id,'threadId',ctl.thread_id,'sourceReplyId',r.id,'intent',classification->>'intent','approved',decision.approved,'policyRevision',p.revision));
  spine:=public.outreach_append_event(p_org,canonical,ARRAY['outreach.conversation.decision'],pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(decision.id::text,'UTF8')),'hex'));
  IF spine->>'result' NOT IN('created','duplicate') OR spine->>'result' IS NULL THEN RAISE EXCEPTION 'agents:event_rejected';END IF;
  RETURN jsonb_build_object('decisionId',decision.id,'approved',decision.approved);
 END IF;
 RAISE EXCEPTION 'agents:invalid';
END $$;
REVOKE ALL ON FUNCTION public.outreach_agent_mutate(uuid,uuid,text,jsonb),public.outreach_reply_decision_is_authorized(uuid,uuid,uuid,bigint,uuid,text,timestamptz) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.outreach_agent_mutate(uuid,uuid,text,jsonb),public.outreach_reply_decision_is_authorized(uuid,uuid,uuid,bigint,uuid,text,timestamptz) TO service_role;
COMMIT;
